import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

/**
 * THE CLIENT ENCODER AND THE PROGRAM'S ARGUMENT LIST MUST AGREE, BYTE FOR BYTE.
 *
 * `subscribe_private_stark` lost its `client_stealth_meta: Option<[u8;64]>`
 * argument, which used to sit between `stark_commitment` and
 * `license_commitment`. This client hand-rolls the Borsh encoding, and it wrote
 * that Option's 1-byte tag EVEN WHEN NONE. Leaving that byte in place does not
 * fail loudly: the program reads `license_commitment`'s Option tag from the
 * stale meta tag (0 = None) and silently drops the license commitment, so every
 * vault created from this client would have no license key and nothing would
 * say so. One byte, no error.
 *
 * `claim_period` stopped declaring `retailer` as a `Signer`. If this client
 * keeps marking it `isSigner: true`, the RUNTIME rejects the transaction for a
 * missing signature before the program is reached — which fails exactly for the
 * merchants the permissionless change exists to rescue, the ones whose retailer
 * key no longer exists.
 *
 * Neither of those is visible to a unit test of an exported function, because
 * both builders are module-private. So this reads the IDL — the program's own
 * generated description of its arguments and accounts — and checks the encoder
 * source against it. The IDL is regenerated by `anchor idl build`, so it cannot
 * drift from the Rust without the Rust changing.
 */

// vitest runs with cwd = apps/extension.
const REPO_ROOT = resolve(process.cwd(), '../..');

interface IdlArg {
  name: string;
  type: unknown;
}
interface IdlAccount {
  name: string;
  signer?: boolean;
  writable?: boolean;
}
interface IdlInstruction {
  name: string;
  args: IdlArg[];
  accounts: IdlAccount[];
}

const idl = JSON.parse(
  readFileSync(resolve(REPO_ROOT, 'target/idl/zk_shielded.json'), 'utf8'),
) as { instructions: IdlInstruction[] };

const instruction = (name: string): IdlInstruction => {
  const ix = idl.instructions.find((i) => i.name === name);
  if (!ix) throw new Error(`no ${name} in the IDL — the instruction was renamed or removed`);
  return ix;
};

/**
 * Borsh byte length of an IDL type, with every `Option` absent.
 *
 * An absent Option is one tag byte and nothing else, which is what both of this
 * client's Options are in the default path.
 */
function borshLenWithOptionsNone(type: unknown): number {
  if (type === 'u64' || type === 'i64') return 8;
  if (type === 'u8' || type === 'bool') return 1;
  if (type === 'pubkey') return 32;
  // [C3-D12] Anchor emits `Vec<u8>` as the shorthand `"bytes"`, NOT as
  // `{ vec: "u8" }` — so `directions` and `siblings` reach this table by two
  // different spellings of the same shape.
  if (type === 'bytes') return 4 + WALK_LEVELS;
  if (typeof type === 'object' && type !== null) {
    const t = type as Record<string, unknown>;
    if ('option' in t) return 1;
    if (Array.isArray(t.array)) return Number(t.array[1]);
    // [C3-D12] Borsh Vec: a u32 length prefix plus WALK_LEVELS elements. A Vec
    // has no constant size, so this table is only meaningful because both Vecs
    // in this instruction are the walk, and the walk has exactly one length —
    // MERKLE_DEPTH minus the depth C3 proves.
    if ('vec' in t) return 4 + WALK_LEVELS * borshLenWithOptionsNone(t.vec);
  }
  throw new Error(`unhandled IDL type in the size table: ${JSON.stringify(type)}`);
}

/**
 * [C3-D12] Merkle levels ABOVE the depth-12 C3 circuit: 15 - 12 = 3.
 *
 * The client walks them on chain to turn C3's subtree root into a pool root.
 * Both `Vec`s in `subscribe_private_stark` carry exactly this many entries, so
 * the instruction has ONE size and the table below is well defined.
 */
const WALK_LEVELS = 3;

const source = readFileSync(
  resolve(process.cwd(), 'src/shared/services/subscriptionVault.ts'),
  'utf8',
);

/**
 * The non-literal terms of the encoder's `Buffer.alloc(...)`, and what each is
 * worth in the default path.
 *
 * ⚠️ THIS USED TO BE "one byte per named term", which was right only while every
 * named term was an absent Option. `walkBytes` is not: it is 43 bytes for a
 * three-level walk. A named term the parser does not recognise now FAILS rather
 * than silently counting as 1 — the direction that catches a drift instead of
 * absorbing it.
 */
const NAMED_ALLOC_TERMS: Record<string, number> = {
  licenseOptionSize: 1,
  walkBytes: 8 + (4 + WALK_LEVELS * 8) + (4 + WALK_LEVELS),
};

/**
 * The numeric literals of a `Buffer.alloc(...)` expression, summed.
 *
 * The encoder writes its budget as `Buffer.alloc(8 + 32 + 32 + ... +
 * licenseOptionSize)`; the named terms are the Option sizes, each 1 when the
 * Option is absent. So: sum of the literals, plus one per named term.
 */
function allocatedBytesWithOptionsNone(fnName: string): number {
  const at = source.indexOf(`function ${fnName}(`);
  expect(at, `${fnName} is gone from subscriptionVault.ts`).toBeGreaterThan(-1);
  const allocAt = source.indexOf('Buffer.alloc(', at);
  expect(allocAt, `${fnName} no longer allocates its instruction data`).toBeGreaterThan(-1);
  const open = allocAt + 'Buffer.alloc('.length;
  const close = source.indexOf(')', open);
  const terms = source
    .slice(open, close)
    .split('+')
    // The encoder's alloc is now a multi-line expression with a trailing comma,
    // so a term can arrive as `walkBytes,`. Strip it — a comma is not part of
    // the name, and leaving it on made the lookup miss and the test fail with a
    // message about a term the source does not contain.
    .map((t) => t.trim().replace(/,$/, ''));
  return terms.reduce((sum, term) => {
    if (/^\d+$/.test(term)) return sum + Number(term);
    const named = NAMED_ALLOC_TERMS[term];
    if (named === undefined) {
      throw new Error(
        `unknown term \`${term}\` in ${fnName}'s Buffer.alloc — add it to ` +
        `NAMED_ALLOC_TERMS with its size, or this test silently counts it as 1`,
      );
    }
    return sum + named;
  }, 0);
}

describe('subscribe_private_stark — hand-rolled Borsh vs the program IDL', () => {
  it('no longer declares client_stealth_meta, on either side', () => {
    // The 64 bytes were a subscriber-controlled stealth address written into a
    // public account to select a refund path that no longer exists. Removing
    // only the WRITE would have left them in the transaction payload, which is
    // just as public — so the argument itself is gone.
    expect(instruction('subscribe_private_stark').args.map((a) => a.name)).not.toContain(
      'client_stealth_meta',
    );
    expect(source).not.toContain('clientStealthMeta');
    expect(source).not.toContain('metaOptionSize');
  });

  it('allocates exactly the bytes the program will deserialise', () => {
    const ix = instruction('subscribe_private_stark');
    const expected =
      8 + ix.args.reduce((sum, a) => sum + borshLenWithOptionsNone(a.type), 0);
    expect(allocatedBytesWithOptionsNone('buildSubscribePrivateStarkIx')).toBe(expected);
  });

  it('puts the C3-D12 walk after license_commitment, and nothing else after it', () => {
    // 🚨 THE OLD ASSERTION WAS "license_commitment is LAST", and its rationale
    // was that nothing sits after it to be shifted by a mis-sized Option tag.
    // Three arguments sit after it since 2026-08-29, so that protection is
    // GONE: a stray tag byte now lands the walk at the wrong offset and the
    // handler folds garbage siblings into a root that matches nothing.
    //
    // The replacement pins the exact order, because the order is what the
    // hand-rolled encoder assumes when it appends the walk at the end.
    const names = instruction('subscribe_private_stark').args.map((a) => a.name);
    expect(names.slice(-4)).toEqual([
      'license_commitment', 'subtree_root', 'siblings', 'directions',
    ]);
  });

  it('the walk is the LAST thing the encoder writes, in that same order', () => {
    // The source-level twin of the assertion above: the IDL order and the
    // encoder's write order are two files that must agree, and only one of them
    // is generated.
    const at = source.indexOf('function buildSubscribePrivateStarkIx(');
    expect(at, 'buildSubscribePrivateStarkIx is gone').toBeGreaterThan(-1);
    const body = source.slice(at, source.indexOf('const keys = [', at));
    const order = ['subtreeRoot, offset', 'siblings.length, offset', 'directions.length, offset'];
    let cursor = body.indexOf('licenseCommitment!');
    expect(cursor).toBeGreaterThan(-1);
    for (const marker of order) {
      const next = body.indexOf(marker, cursor);
      expect(next, `${marker} is not written after the license option`).toBeGreaterThan(cursor);
      cursor = next;
    }
  });
});

describe('claim_period — the permissionless account shape', () => {
  it('is not a signer in the IDL', () => {
    const retailer = instruction('claim_period').accounts.find((a) => a.name === 'retailer');
    expect(retailer, 'claim_period no longer declares a retailer account').toBeDefined();
    expect(retailer!.signer ?? false).toBe(false);
    // It still has to be writable: it is the destination for the payout and,
    // on the final claim, for the vault's rent.
    expect(retailer!.writable).toBe(true);
  });

  it('is not marked a signer by the client either', () => {
    const at = source.indexOf('function buildClaimPeriodIx(');
    expect(at, 'buildClaimPeriodIx is gone').toBeGreaterThan(-1);
    const keysAt = source.indexOf('const keys = [', at);
    const firstKey = source.slice(keysAt, source.indexOf(']', keysAt));
    expect(firstKey).toContain('{ pubkey: retailer, isSigner: false, isWritable: true }');
  });

  it('reads the retailer off the vault instead of assuming the local wallet', () => {
    // The old code passed `signer.publicKey` as the retailer. Combined with a
    // non-signing account that would send a claim naming the WRONG payee, which
    // the program rejects with Unauthorized — so this is not cosmetic.
    const at = source.indexOf('export async function claimPeriod(');
    expect(at).toBeGreaterThan(-1);
    const body = source.slice(at, source.indexOf('\n}', at));
    expect(body).toContain('buildClaimPeriodIx(new PublicKey(vault.retailer)');
    expect(body).not.toContain('buildClaimPeriodIx(signer.publicKey');
  });
});
