import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

/**
 * THE CLIENT ENCODER AND THE PROGRAM'S ARGUMENT LIST MUST AGREE, BYTE FOR BYTE.
 *
 * `subscribe_private_stark` lost its `client_stealth_meta: Option<[u8;64]>`
 * argument, which used to sit between `stark_commitment` and
 * `license_commitment`. This client hand-rolls the Borsh encoding, and it wrote
 * that Option's 1-byte tag EVEN WHEN NONE. Leaving that byte in place does not
 * fail loudly: the program reads `license_commitment`'s Option tag from the
 * stale meta tag (0 = None) and silently drops the license commitment, so every
 * vault created from this client would have no license key and nothing would
 * say so. One byte, no error.
 *
 * `claim_period` stopped declaring `retailer` as a `Signer`. If this client
 * keeps marking it `isSigner: true`, the RUNTIME rejects the transaction for a
 * missing signature before the program is reached — which fails exactly for the
 * merchants the permissionless change exists to rescue, the ones whose retailer
 * key no longer exists.
 *
 * Neither of those is visible to a unit test of an exported function, because
 * both builders are module-private. So this reads the IDL — the program's own
 * generated description of its arguments and accounts — and checks the encoder
 * source against it. The IDL is regenerated by `anchor idl build`, so it cannot
 * drift from the Rust without the Rust changing.
 */

// vitest runs with cwd = apps/extension.
const REPO_ROOT = resolve(process.cwd(), '../..');

interface IdlArg {
  name: string;
  type: unknown;
}
interface IdlAccount {
  name: string;
  signer?: boolean;
  writable?: boolean;
}
interface IdlInstruction {
  name: string;
  args: IdlArg[];
  accounts: IdlAccount[];
}

const idl = JSON.parse(
  readFileSync(resolve(REPO_ROOT, 'target/idl/zk_shielded.json'), 'utf8'),
) as { instructions: IdlInstruction[] };

const instruction = (name: string): IdlInstruction => {
  const ix = idl.instructions.find((i) => i.name === name);
  if (!ix) throw new Error(`no ${name} in the IDL — the instruction was renamed or removed`);
  return ix;
};

/**
 * Borsh byte length of an IDL type, with every `Option` absent.
 *
 * An absent Option is one tag byte and nothing else, which is what both of this
 * client's Options are in the default path.
 */
function borshLenWithOptionsNone(type: unknown): number {
  if (type === 'u64' || type === 'i64') return 8;
  if (type === 'u8' || type === 'bool') return 1;
  if (type === 'pubkey') return 32;
  if (typeof type === 'object' && type !== null) {
    const t = type as Record<string, unknown>;
    if ('option' in t) return 1;
    if (Array.isArray(t.array)) return Number(t.array[1]);
  }
  throw new Error(`unhandled IDL type in the size table: ${JSON.stringify(type)}`);
}

const source = readFileSync(
  resolve(process.cwd(), 'src/shared/services/subscriptionVault.ts'),
  'utf8',
);

/**
 * The numeric literals of a `Buffer.alloc(...)` expression, summed.
 *
 * The encoder writes its budget as `Buffer.alloc(8 + 32 + 32 + ... +
 * licenseOptionSize)`; the named terms are the Option sizes, each 1 when the
 * Option is absent. So: sum of the literals, plus one per named term.
 */
function allocatedBytesWithOptionsNone(fnName: string): number {
  const at = source.indexOf(`function ${fnName}(`);
  expect(at, `${fnName} is gone from subscriptionVault.ts`).toBeGreaterThan(-1);
  const allocAt = source.indexOf('Buffer.alloc(', at);
  expect(allocAt, `${fnName} no longer allocates its instruction data`).toBeGreaterThan(-1);
  const open = allocAt + 'Buffer.alloc('.length;
  const close = source.indexOf(')', open);
  const terms = source
    .slice(open, close)
    .split('+')
    .map((t) => t.trim());
  return terms.reduce((sum, term) => sum + (/^\d+$/.test(term) ? Number(term) : 1), 0);
}

describe('subscribe_private_stark — hand-rolled Borsh vs the program IDL', () => {
  it('no longer declares client_stealth_meta, on either side', () => {
    // The 64 bytes were a subscriber-controlled stealth address written into a
    // public account to select a refund path that no longer exists. Removing
    // only the WRITE would have left them in the transaction payload, which is
    // just as public — so the argument itself is gone.
    expect(instruction('subscribe_private_stark').args.map((a) => a.name)).not.toContain(
      'client_stealth_meta',
    );
    expect(source).not.toContain('clientStealthMeta');
    expect(source).not.toContain('metaOptionSize');
  });

  it('allocates exactly the bytes the program will deserialise', () => {
    const ix = instruction('subscribe_private_stark');
    const expected =
      8 + ix.args.reduce((sum, a) => sum + borshLenWithOptionsNone(a.type), 0);
    expect(allocatedBytesWithOptionsNone('buildSubscribePrivateStarkIx')).toBe(expected);
  });

  it('keeps license_commitment LAST, which is what makes a stray tag byte silent', () => {
    const args = instruction('subscribe_private_stark').args;
    expect(args[args.length - 1]!.name).toBe('license_commitment');
  });
});

describe('claim_period — the permissionless account shape', () => {
  it('is not a signer in the IDL', () => {
    const retailer = instruction('claim_period').accounts.find((a) => a.name === 'retailer');
    expect(retailer, 'claim_period no longer declares a retailer account').toBeDefined();
    expect(retailer!.signer ?? false).toBe(false);
    // It still has to be writable: it is the destination for the payout and,
    // on the final claim, for the vault's rent.
    expect(retailer!.writable).toBe(true);
  });

  it('is not marked a signer by the client either', () => {
    const at = source.indexOf('function buildClaimPeriodIx(');
    expect(at, 'buildClaimPeriodIx is gone').toBeGreaterThan(-1);
    const keysAt = source.indexOf('const keys = [', at);
    const firstKey = source.slice(keysAt, source.indexOf(']', keysAt));
    expect(firstKey).toContain('{ pubkey: retailer, isSigner: false, isWritable: true }');
  });

  it('reads the retailer off the vault instead of assuming the local wallet', () => {
    // The old code passed `signer.publicKey` as the retailer. Combined with a
    // non-signing account that would send a claim naming the WRONG payee, which
    // the program rejects with Unauthorized — so this is not cosmetic.
    const at = source.indexOf('export async function claimPeriod(');
    expect(at).toBeGreaterThan(-1);
    const body = source.slice(at, source.indexOf('\n}', at));
    expect(body).toContain('buildClaimPeriodIx(new PublicKey(vault.retailer)');
    expect(body).not.toContain('buildClaimPeriodIx(signer.publicKey');
  });
});
