[package]
name = "p01-bundler"
version = "0.1.0"
description = "P01 On-chain Privacy Bundler — atomic multi-shield CPI batching"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "p01_bundler"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.32.1"
anchor-spl = "0.32.1"
