import { PublicKey } from '@solana/web3.js';
import type { Cluster } from './types';

// ============================================================================
// Program IDs
// ============================================================================
//
// The block between the <auto-generated-program-ids> sentinels is managed by
// scripts/sync-program-ids.ts. Run `pnpm sync-program-ids --write` after
// editing Anchor.toml to regenerate it. Do not hand-edit between the sentinels.

// <auto-generated-program-ids>
export const PROGRAM_IDS: Record<Cluster, PublicKey> = {
  'mainnet-beta': new PublicKey('2tuztgD9RhdaBkiP79fHkrFbfWBX75v7UjSNN4ULfbSp'),
  'testnet': PublicKey.default,
  // devnet runs the reworked v2 stealth program (chunked KEM announcement +
  // getProgramAccounts scan). See specter-stealth-onchain-transport notes.
  'devnet': new PublicKey('FgKhXakZGsd4PdiGgACYy8gwj1JLMYA691yQr2PhUNfL'),
  'localnet': new PublicKey('2tuztgD9RhdaBkiP79fHkrFbfWBX75v7UjSNN4ULfbSp'),
};

export const REGISTRY_PROGRAM_IDS: Record<Cluster, PublicKey> = {
  'mainnet-beta': PublicKey.default,
  'testnet': PublicKey.default,
  'devnet': new PublicKey('QaQwpvBi1EQpevNE21D2oNBHFsLtoLwa7aXH26zRhQB'),
  'localnet': new PublicKey('QaQwpvBi1EQpevNE21D2oNBHFsLtoLwa7aXH26zRhQB'),
};

export const RELAYER_PROGRAM_IDS: Record<Cluster, PublicKey> = {
  'mainnet-beta': PublicKey.default,
  'testnet': PublicKey.default,
  'devnet': new PublicKey('Ud2JYaq4frePBy3L2DmddmtPT3nXC1nqxsXEX934Hbw'),
  'localnet': new PublicKey('2okhzLVr6FEq5jP19KT6VurcSutx2zE4RhkRamrk5WpW'),
};

/** Registry program ID (devnet). Convenience alias for REGISTRY_PROGRAM_IDS.devnet. */
export const REGISTRY_PROGRAM_ID = new PublicKey('QaQwpvBi1EQpevNE21D2oNBHFsLtoLwa7aXH26zRhQB');
// </auto-generated-program-ids>

/**
 * Default program ID (devnet)
 */
export const DEFAULT_PROGRAM_ID = PROGRAM_IDS['devnet'];

/**
 * Get a program ID for the given cluster, with a safety check for mainnet-beta.
 *
 * Throws a clear error if the caller requests a program ID that hasn't been
 * deployed yet (i.e. still set to PublicKey.default).
 *
 * @param ids - The program ID map to look up
 * @param cluster - The target cluster
 * @param programName - Human-readable program name for the error message
 * @returns The program ID for the requested cluster
 */
export function getCheckedProgramId(
  ids: Record<Cluster, PublicKey>,
  cluster: Cluster,
  programName: string = 'Protocol 01',
): PublicKey {
  const id = ids[cluster];
  if (id.equals(PublicKey.default)) {
    if (cluster === 'mainnet-beta') {
      throw new Error(
        `${programName} is not yet deployed on mainnet-beta. Use 'devnet' for testing.`
      );
    }
    throw new Error(
      `${programName} is not yet deployed on ${cluster}. Use 'devnet' for testing.`
    );
  }
  return id;
}

// ============================================================================
// RPC Endpoints
// ============================================================================

/**
 * Default RPC endpoints for different clusters.
 *
 * For richer endpoint resolution with Helius/QuickNode fallback, use
 * `getEndpoints()` or `RpcConnectionManager` from `@protocol-01/rpc-config`.
 */
export const RPC_ENDPOINTS: Record<Cluster, string> = {
  'mainnet-beta': 'https://api.mainnet-beta.solana.com',
  'testnet': 'https://api.testnet.solana.com',
  'devnet': 'https://api.devnet.solana.com',
  'localnet': 'http://127.0.0.1:8899',
};

/** Custom RPC endpoint overrides set at runtime */
const _customRpcEndpoints: Partial<Record<Cluster, string>> = {};

/**
 * Override the RPC endpoint for a given cluster at runtime.
 *
 * This is useful for switching to a premium provider (Helius, QuickNode, etc.)
 * without changing code. The override persists for the lifetime of the process.
 *
 * @param cluster - The cluster to override
 * @param url - The custom RPC endpoint URL
 *
 * @example
 * ```ts
 * import { setCustomRpcEndpoint } from '@protocol-01/specter-sdk';
 * setCustomRpcEndpoint('devnet', 'https://devnet.helius-rpc.com/?api-key=YOUR_KEY');
 * ```
 */
export function setCustomRpcEndpoint(cluster: Cluster, url: string): void {
  _customRpcEndpoints[cluster] = url;
}

/**
 * Get the effective RPC endpoint for a cluster.
 * Returns the custom override if set, otherwise the default.
 */
export function getEffectiveRpcEndpoint(cluster: Cluster): string {
  return _customRpcEndpoints[cluster] ?? RPC_ENDPOINTS[cluster];
}

/**
 * Known public RPC endpoints (rate-limited, not suitable for production).
 * Used to detect when a user hasn't configured a custom endpoint.
 */
const PUBLIC_RPC_HOSTS = [
  'api.mainnet-beta.solana.com',
  'api.testnet.solana.com',
  'api.devnet.solana.com',
];

/**
 * Returns true if the given endpoint is a public Solana RPC (rate-limited).
 */
export function isPublicRpcEndpoint(url: string): boolean {
  try {
    const host = new URL(url).hostname;
    return PUBLIC_RPC_HOSTS.includes(host);
  } catch {
    return false;
  }
}

// ============================================================================
// Wallet Constants
// ============================================================================

/**
 * Default derivation path for Solana wallets
 */
export const DEFAULT_DERIVATION_PATH = "m/44'/501'/0'/0'";

/**
 * Stealth key derivation paths
 */
export const STEALTH_DERIVATION = {
  SPENDING_KEY_PATH: "m/44'/501'/0'/1'",
  VIEWING_KEY_PATH: "m/44'/501'/0'/2'",
};

/**
 * Default entropy strength for mnemonic generation (24 words)
 */
export const DEFAULT_MNEMONIC_STRENGTH = 256;

// ============================================================================
// Transaction Constants
// ============================================================================

/**
 * Lamports per SOL
 */
export const LAMPORTS_PER_SOL = 1_000_000_000n;

/**
 * Minimum rent exemption (approx)
 */
export const MIN_RENT_EXEMPTION = 890_880n;

/**
 * Default transaction timeout (60 seconds)
 */
export const DEFAULT_TX_TIMEOUT = 60_000;

/**
 * Maximum retries for transaction confirmation
 */
export const MAX_TX_RETRIES = 3;

/**
 * Delay between retries (ms)
 */
export const TX_RETRY_DELAY = 1_000;

// ============================================================================
// Stealth Address Constants
// ============================================================================

/**
 * Stealth address prefix for encoding
 */
export const STEALTH_ADDRESS_PREFIX = 'st';

/**
 * View tag size in bytes
 */
export const VIEW_TAG_SIZE = 1;

/**
 * Ephemeral key size in bytes
 */
export const EPHEMERAL_KEY_SIZE = 32;

/**
 * Stealth meta-address version (v1: classic ECDH only)
 */
export const STEALTH_META_ADDRESS_VERSION = 1;

/**
 * Stealth meta-address version 2 (hybrid X25519 + ML-KEM-768)
 */
export const STEALTH_META_ADDRESS_VERSION_2 = 2;

/**
 * ML-KEM-768 sizes in bytes (FIPS 203)
 */
export const KEM_PUBLIC_KEY_SIZE = 1184;
export const KEM_SECRET_KEY_SIZE = 2400;
export const KEM_CIPHERTEXT_SIZE = 1088;
export const KEM_SHARED_SECRET_SIZE = 32;

/**
 * HKDF info strings for hybrid stealth derivation.
 * Exported as Uint8Array because @noble/hashes v2 requires byte-array info params.
 */
import { utf8ToBytes } from '@noble/hashes/utils.js';
export const HYBRID_HKDF_INFO = utf8ToBytes('p01-hybrid-stealth-v2');
export const STEALTH_SEED_INFO = utf8ToBytes('p01-stealth-seed');

// ============================================================================
// Stream Constants
// ============================================================================

/**
 * Minimum stream duration (1 hour in seconds)
 */
export const MIN_STREAM_DURATION = 3600;

/**
 * Maximum stream duration (5 years in seconds)
 */
export const MAX_STREAM_DURATION = 5 * 365 * 24 * 3600;

/**
 * Minimum stream amount in lamports
 */
export const MIN_STREAM_AMOUNT = 1_000_000n; // 0.001 SOL

/**
 * Stream PDA seeds
 */
export const STREAM_SEED = 'specter_stream';

// ============================================================================
// Privacy Constants
// ============================================================================

/**
 * Default split count for enhanced privacy
 */
export const DEFAULT_SPLIT_COUNT = 3;

/**
 * Default delay between splits (ms)
 */
export const DEFAULT_SPLIT_DELAY = 5_000;

/**
 * Minimum amount per split transaction (lamports)
 */
export const MIN_SPLIT_AMOUNT = 10_000_000n; // 0.01 SOL

/**
 * Privacy level configurations
 */
export const PRIVACY_CONFIG = {
  standard: {
    useStealth: true,
    splitCount: 1,
    useDelay: false,
    useRelayer: false,
  },
  enhanced: {
    useStealth: true,
    splitCount: 3,
    useDelay: true,
    delayMs: 10_000,
    useRelayer: false,
  },
  maximum: {
    useStealth: true,
    splitCount: 5,
    useDelay: true,
    delayMs: 30_000,
    useRelayer: true,
    multiHop: true,
  },
} as const;

// ============================================================================
// Crypto Constants
// ============================================================================

/**
 * Encryption algorithm
 */
export const ENCRYPTION_ALGORITHM = 'aes-256-gcm';

/**
 * Key derivation function iterations
 */
export const KDF_ITERATIONS = 100_000;

/**
 * Salt size for encryption
 */
export const SALT_SIZE = 16;

/**
 * IV size for AES-GCM
 */
export const IV_SIZE = 12;

/**
 * Auth tag size for AES-GCM
 */
export const AUTH_TAG_SIZE = 16;

// ============================================================================
// Error Messages
// ============================================================================

export const ERROR_MESSAGES = {
  WALLET_NOT_CONNECTED: 'Wallet is not connected. Please connect a wallet first.',
  INVALID_SEED_PHRASE: 'Invalid seed phrase. Please check and try again.',
  INSUFFICIENT_BALANCE: 'Insufficient balance for this transaction.',
  INVALID_RECIPIENT: 'Invalid recipient address format.',
  STEALTH_GENERATION_FAILED: 'Failed to generate stealth address.',
  STREAM_NOT_FOUND: 'Stream not found or has been cancelled.',
  UNAUTHORIZED: 'You are not authorized to perform this action.',
  RPC_ERROR: 'Failed to connect to the Solana network.',
  TIMEOUT: 'Transaction confirmation timed out.',
} as const;

// ============================================================================
// Anchor IDL Account Names
// ============================================================================

export const ACCOUNT_NAMES = {
  STEALTH_ACCOUNT: 'StealthAccount',
  STREAM_ACCOUNT: 'StreamAccount',
  USER_REGISTRY: 'UserRegistry',
} as const;

// ============================================================================
// Feature Flags
// ============================================================================

/**
 * Default feature flag values. These are the compile-time defaults.
 * Use `setFeature()` to override at runtime without changing these.
 */
export const FEATURES = {
  ENABLE_RELAYER: false, // Enable when relayer is deployed
  ENABLE_MULTI_HOP: false, // Enable when multi-hop is implemented
  ENABLE_TOKEN_STREAMS: true, // SPL token streams
  ENABLE_NFT_TRANSFERS: false, // NFT stealth transfers
} as const;

/**
 * Feature flag type — the set of known feature names.
 */
export type FeatureName = keyof typeof FEATURES;

/** Runtime overrides for feature flags */
const _featureOverrides: Partial<Record<string, boolean>> = {};

/**
 * Enable or disable a feature flag at runtime.
 *
 * @param name - Feature flag name (e.g. 'ENABLE_RELAYER')
 * @param enabled - Whether the feature should be enabled
 *
 * @example
 * ```ts
 * import { setFeature } from '@protocol-01/specter-sdk';
 * setFeature('ENABLE_RELAYER', true);
 * ```
 */
export function setFeature(name: string, enabled: boolean): void {
  _featureOverrides[name] = enabled;
}

/**
 * Get the effective value of a feature flag.
 * Returns the runtime override if set, otherwise the compile-time default.
 *
 * @param name - Feature flag name
 * @returns Whether the feature is enabled
 *
 * @example
 * ```ts
 * import { getFeature } from '@protocol-01/specter-sdk';
 * if (getFeature('ENABLE_RELAYER')) {
 *   // relay is enabled
 * }
 * ```
 */
export function getFeature(name: string): boolean {
  if (name in _featureOverrides) {
    return _featureOverrides[name]!;
  }
  if (name in FEATURES) {
    return FEATURES[name as FeatureName];
  }
  return false;
}
