# Protocol 01 Hackathon Startup Script
# This script starts all services needed for the demo

Write-Host "============================================" -ForegroundColor Cyan
Write-Host "   Protocol 01 - Hackathon Demo Startup" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan
Write-Host ""

# Check if pnpm is installed
if (!(Get-Command pnpm -ErrorAction SilentlyContinue)) {
    Write-Host "[ERROR] pnpm is not installed. Please install it first." -ForegroundColor Red
    exit 1
}

# Start the relayer
Write-Host "[1/3] Starting ZK Prover Relayer..." -ForegroundColor Yellow
$relayerJob = Start-Job -ScriptBlock {
    Set-Location "P:\Protocol 01\services\relayer"
    pnpm dev
}
Start-Sleep -Seconds 3

# Check if relayer started
$relayerRunning = Test-NetConnection -ComputerName localhost -Port 3000 -WarningAction SilentlyContinue
if ($relayerRunning.TcpTestSucceeded) {
    Write-Host "[OK] Relayer running on port 3000" -ForegroundColor Green
} else {
    Write-Host "[ERROR] Relayer failed to start" -ForegroundColor Red
    exit 1
}

# Start localtunnel for public access
Write-Host "[2/3] Creating public tunnel..." -ForegroundColor Yellow
$tunnelJob = Start-Job -ScriptBlock {
    npx localtunnel --port 3000
}
Start-Sleep -Seconds 5

# Get tunnel URL
$tunnelOutput = Receive-Job -Job $tunnelJob -Keep
$tunnelUrl = $tunnelOutput | Select-String -Pattern "https://.*\.loca\.lt" | ForEach-Object { $_.Matches[0].Value }

if ($tunnelUrl) {
    Write-Host "[OK] Public URL: $tunnelUrl" -ForegroundColor Green

    # Update mobile app config
    $envContent = @"
# Protocol 01 Mobile Environment Variables
# Auto-generated by hackathon startup script

# ZK Relayer URL
EXPO_PUBLIC_RELAYER_URL=$tunnelUrl

# Privy Auth
EXPO_PUBLIC_PRIVY_APP_ID=cmkunrdg605ouie0blb3kq1fm

# Network
EXPO_PUBLIC_SOLANA_NETWORK=devnet

# Fees
EXPO_PUBLIC_PLATFORM_FEE_BPS=25
EXPO_PUBLIC_P01_NETWORK_FEE_BPS=50
"@
    $envContent | Out-File -FilePath "P:\Protocol 01\apps\mobile\.env" -Encoding UTF8
    Write-Host "[OK] Updated apps/mobile/.env with tunnel URL" -ForegroundColor Green
} else {
    Write-Host "[WARN] Could not get tunnel URL, using default" -ForegroundColor Yellow
}

Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host "   Services Started Successfully!" -ForegroundColor Green
Write-Host "============================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Relayer: http://localhost:3000" -ForegroundColor White
Write-Host "Public:  $tunnelUrl" -ForegroundColor White
Write-Host ""
Write-Host "To start the mobile app:" -ForegroundColor Yellow
Write-Host "  cd apps/mobile && pnpm start" -ForegroundColor White
Write-Host ""
Write-Host "Press Ctrl+C to stop all services" -ForegroundColor Gray

# Keep script running
try {
    while ($true) {
        Start-Sleep -Seconds 10
    }
} finally {
    Write-Host "Stopping services..." -ForegroundColor Yellow
    Stop-Job -Job $relayerJob, $tunnelJob
    Remove-Job -Job $relayerJob, $tunnelJob
}
