#!/usr/bin/env node
/**
 * inline-wasm.mjs — Generate `src/wasmData.ts` from `@protocol-01/stark-prover`.
 *
 * Reads `p01_stark_bg.wasm` (~124 KB) from the sibling workspace package,
 * base64-encodes it (~165 KB), and writes a TypeScript module that exports
 * the encoded blob as `STARK_WASM_BASE64`. This file is consumed by
 * `src/ZKProver.tsx` so the WASM ships inside the package's JS bundle
 * (no runtime fetch, no `.wasm` asset registration in metro.config.js).
 *
 * 🚨 RESOLUTION ORDER, AND IT WAS BACKWARDS UNTIL 2026-08-25.
 *
 * It tried `node_modules` FIRST and the workspace sibling second. node_modules
 * holds whatever version was last PUBLISHED to npm; the sibling is the source of
 * truth this repo builds. So a stale published tarball silently won, and this
 * file generated `wasmData.ts` from it.
 *
 * MEASURED, and it is why this comment exists rather than a one-line swap: the
 * generated `src/wasmData.ts` header records "Raw size: 124562 bytes" — a THIRD
 * generation of the blob, against 229,640 for the coset build the deployed
 * verifier accepts and 192,732 for the pre-coset build it rejects. React Native
 * was shipping a prover no deployed verifier has ever accepted, and nothing said
 * so: a rejected proof fails at the END of a ~150-transaction upload.
 *
 * Resolution order (first hit wins):
 *   1. ../stark-prover/wasm/p01_stark_bg.wasm
 *      THE WORKSPACE SIBLING. What this repo builds, and what
 *      `packages/stark-prover/src/shippedBlob.test.ts` pins.
 *   2. node_modules/@protocol-01/stark-prover/wasm/p01_stark_bg.wasm
 *      the published copy — a fallback for consumers building outside the
 *      monorepo, never the preferred source inside it.
 *
 * Idempotent. Logs the input + base64 sizes.
 *
 * Hooked into `prepublishOnly` so the published tarball always carries
 * a fresh `wasmData.ts`.
 */

import { readFileSync, writeFileSync, statSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const PKG_ROOT = resolve(__dirname, '..');

// ⛔ The workspace sibling FIRST. See the header — the other order shipped a
// third-generation blob to React Native for months.
const CANDIDATES = [
  resolve(PKG_ROOT, '../stark-prover/wasm/p01_stark_bg.wasm'),
  resolve(PKG_ROOT, 'node_modules/@protocol-01/stark-prover/wasm/p01_stark_bg.wasm'),
  resolve(PKG_ROOT, '../../node_modules/@protocol-01/stark-prover/wasm/p01_stark_bg.wasm'),
];

function findWasm() {
  for (const candidate of CANDIDATES) {
    try {
      const stat = statSync(candidate);
      if (stat.isFile() && stat.size > 0) return candidate;
    } catch {
      // not present, try next
    }
  }
  throw new Error(
    `Could not locate p01_stark_bg.wasm. Tried:\n  - ${CANDIDATES.join('\n  - ')}\n` +
    'Ensure @protocol-01/stark-prover is installed (pnpm install) or that the ' +
    'workspace sibling exists at ../stark-prover/wasm/.'
  );
}

const wasmPath = findWasm();
const wasmBytes = readFileSync(wasmPath);
const base64 = wasmBytes.toString('base64');

const out = resolve(PKG_ROOT, 'src/wasmData.ts');
const banner = `/**
 * Auto-generated by scripts/inline-wasm.mjs — DO NOT EDIT BY HAND.
 *
 * Source: ${wasmPath.replace(/\\\\/g, '/').replace(PKG_ROOT.replace(/\\\\/g, '/'), '<pkg>')}
 * Raw size: ${wasmBytes.length} bytes
 * Base64 size: ${base64.length} chars
 *
 * Regenerate with: pnpm --filter @protocol-01/react-native-zk inline-wasm
 */

export const STARK_WASM_BASE64 = '${base64}';
`;

writeFileSync(out, banner, 'utf8');

console.log(`[inline-wasm] read    ${wasmPath}`);
console.log(`[inline-wasm] raw     ${wasmBytes.length.toLocaleString()} bytes`);
console.log(`[inline-wasm] base64  ${base64.length.toLocaleString()} chars`);
console.log(`[inline-wasm] wrote   ${out}`);
