#!/usr/bin/env node
/**
 * inline-wasm.mjs — Generate `src/wasmData.ts` from `@protocol-01/stark-prover`.
 *
 * Reads `p01_stark_bg.wasm` (~124 KB) from the sibling workspace package,
 * base64-encodes it (~165 KB), and writes a TypeScript module that exports
 * the encoded blob as `STARK_WASM_BASE64`. This file is consumed by
 * `src/ZKProver.tsx` so the WASM ships inside the package's JS bundle
 * (no runtime fetch, no `.wasm` asset registration in metro.config.js).
 *
 * Resolution order (first hit wins):
 *   1. node_modules/@protocol-01/stark-prover/wasm/p01_stark_bg.wasm
 *      (works after `pnpm install` once devDeps are installed)
 *   2. ../stark-prover/wasm/p01_stark_bg.wasm
 *      (workspace-relative — works during local development before
 *      pnpm has linked node_modules)
 *
 * Idempotent. Logs the input + base64 sizes.
 *
 * Hooked into `prepublishOnly` so the published tarball always carries
 * a fresh `wasmData.ts`.
 */

import { readFileSync, writeFileSync, statSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const PKG_ROOT = resolve(__dirname, '..');

const CANDIDATES = [
  resolve(PKG_ROOT, 'node_modules/@protocol-01/stark-prover/wasm/p01_stark_bg.wasm'),
  resolve(PKG_ROOT, '../stark-prover/wasm/p01_stark_bg.wasm'),
  resolve(PKG_ROOT, '../../node_modules/@protocol-01/stark-prover/wasm/p01_stark_bg.wasm'),
];

function findWasm() {
  for (const candidate of CANDIDATES) {
    try {
      const stat = statSync(candidate);
      if (stat.isFile() && stat.size > 0) return candidate;
    } catch {
      // not present, try next
    }
  }
  throw new Error(
    `Could not locate p01_stark_bg.wasm. Tried:\n  - ${CANDIDATES.join('\n  - ')}\n` +
    'Ensure @protocol-01/stark-prover is installed (pnpm install) or that the ' +
    'workspace sibling exists at ../stark-prover/wasm/.'
  );
}

const wasmPath = findWasm();
const wasmBytes = readFileSync(wasmPath);
const base64 = wasmBytes.toString('base64');

const out = resolve(PKG_ROOT, 'src/wasmData.ts');
const banner = `/**
 * Auto-generated by scripts/inline-wasm.mjs — DO NOT EDIT BY HAND.
 *
 * Source: ${wasmPath.replace(/\\\\/g, '/').replace(PKG_ROOT.replace(/\\\\/g, '/'), '<pkg>')}
 * Raw size: ${wasmBytes.length} bytes
 * Base64 size: ${base64.length} chars
 *
 * Regenerate with: pnpm --filter @protocol-01/react-native-zk inline-wasm
 */

export const STARK_WASM_BASE64 = '${base64}';
`;

writeFileSync(out, banner, 'utf8');

console.log(`[inline-wasm] read    ${wasmPath}`);
console.log(`[inline-wasm] raw     ${wasmBytes.length.toLocaleString()} bytes`);
console.log(`[inline-wasm] base64  ${base64.length.toLocaleString()} chars`);
console.log(`[inline-wasm] wrote   ${out}`);
