import { PublicKey } from '@solana/web3.js';
import type { Network, ProgramIds, TokenInfo } from './types';

// ─── Program IDs ──────────────────────────────────────────────────────────────
//
// The block between the <auto-generated-program-ids> sentinels is managed by
// scripts/sync-program-ids.ts. Run `pnpm sync-program-ids --write` after
// editing Anchor.toml to regenerate it. Do not hand-edit between the sentinels.

// <auto-generated-program-ids>
export const PROGRAM_IDS: Record<Network, ProgramIds> = {
  devnet: {
    zkShielded: new PublicKey('GbVM5yvetrSD194Hnn1BXnR56F8ZWNKnij7DoVP9j27c'),
    relayer: new PublicKey('2okhzLVr6FEq5jP19KT6VurcSutx2zE4RhkRamrk5WpW'),
    registry: new PublicKey('QaQwpvBi1EQpevNE21D2oNBHFsLtoLwa7aXH26zRhQB'),
    starkVerifier: new PublicKey('DGY37k3Jt7cbrfNa9rxyLZVcFB7S7A2NqtVpkh9fWQvs'),
  },
  mainnet: {
    zkShielded: new PublicKey('8dK17NxQUFPWsLg7eJphiCjSyVfBk2ywC5GU6ctK4qrY'),
    relayer: new PublicKey('11111111111111111111111111111111'), // not yet deployed
    registry: new PublicKey('11111111111111111111111111111111'), // not yet deployed
    starkVerifier: new PublicKey('11111111111111111111111111111111'), // not yet deployed
  },
};
// </auto-generated-program-ids>

/**
 * WHICH OF THOSE IDS ARE ACTUALLY ON DEVNET, measured rather than declared.
 *
 * The block above is regenerated from `Anchor.toml`, and Anchor.toml records
 * what a program's id WOULD be, not whether anything is deployed at it. Two of
 * these carried that warning as an inline comment and the generator wiped it on
 * the next `--write`, which is what an auto-generated block does to a
 * hand-verified fact. So it lives out here, where it survives.
 *
 * Re-checked with `solana account <id> --url devnet` on 2026-08-18:
 *
 *   zkShielded  GbVM5yve…  EXISTS, executable  (upgraded that day)
 *
 * [2026-09-23] `trustless`, `zkspl`, `stream`, `subscription`, `whitelist`
 * and `bundler` LEFT this table (2.0.0). None of them had a program deployed
 * on devnet (zkspl AY38smtd…, stream C92xDDAt…, subscription 3eDvPJTK… and
 * whitelist 5PSYrjBK… read ABSENT; trustless was a placeholder; bundler was in
 * no Anchor.toml), and the modules that read them (confidential, streams,
 * subscriptions, payroll, shield) were removed with them. Subscriptions live
 * inside zk_shielded as vaults. ⛔ `scripts/sync-program-ids.ts` must not
 * re-emit these keys either; `ProgramIds` no longer has them.
 *
 * [2026-09-13] `specter`, `feeSplitter`, `quantumVault` and `arcium` LEFT this
 * table (2.0.0). The founder had specter `FgKhXakZ…`, p01_fee_splitter
 * `UdxXEvcA…`, p01_quantum_vault `9yVr79Xk…` (and p01_quantum_wallet
 * `D7RBAFcM…`) closed on devnet that day — `solana program close`, the ids are
 * unusable for good — and the modules that spoke to them (`stealth`, `vault`)
 * went with them. `arcium` had been a placeholder for a product that left
 * earlier. ⛔ `scripts/sync-program-ids.ts` must not re-emit any of the four
 * on its next `--write`; `ProgramIds` no longer has the keys, so a stale
 * generator fails the type check rather than silently pointing at a closed
 * program.
 */

/**
 * Get the declared program IDs for a given network, minus placeholders.
 * Programs with placeholder IDs (System Program) are excluded and a warning is logged for each.
 *
 * It does not check the chain: an id it returns comes from Anchor.toml and may
 * have no program behind it (the mainnet zkShielded id is declared but nothing
 * is deployed on mainnet).
 * Read the account on the cluster before relying on a module.
 *
 * @param network - The target network ('devnet' or 'mainnet')
 * @returns A partial ProgramIds object without the placeholder entries
 */
export function getDeployedProgramIds(network: Network): Partial<ProgramIds> {
  const PLACEHOLDER = '11111111111111111111111111111111';
  const all = PROGRAM_IDS[network];
  if (!all) {
    throw new Error(`getDeployedProgramIds: unknown network "${network}". Expected "devnet" or "mainnet".`);
  }

  const deployed: Partial<ProgramIds> = {};
  const undeployed: string[] = [];

  for (const [name, pubkey] of Object.entries(all)) {
    if ((pubkey as PublicKey).toBase58() === PLACEHOLDER) {
      undeployed.push(name);
    } else {
      (deployed as any)[name] = pubkey;
    }
  }

  if (undeployed.length > 0) {
    console.warn(
      `[Protocol01] The following programs are not yet deployed on ${network}: ${undeployed.join(', ')}. ` +
      `These modules will not be available.`,
    );
  }

  return deployed;
}

// ─── Token Registry ───────────────────────────────────────────────────────────

export const TOKENS: Record<Network, Record<string, TokenInfo>> = {
  devnet: {
    SOL: {
      symbol: 'SOL',
      mint: new PublicKey('So11111111111111111111111111111111111111112'),
      decimals: 9,
    },
    USDC: {
      symbol: 'USDC',
      mint: new PublicKey('4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU'),
      decimals: 6,
    },
    USDT: {
      symbol: 'USDT',
      mint: new PublicKey('EJwZgeZrdC8TXTQbQBoL6bfuAnFUQQRb18wrLowMGerG'),
      decimals: 6,
    },
  },
  mainnet: {
    SOL: {
      symbol: 'SOL',
      mint: new PublicKey('So11111111111111111111111111111111111111112'),
      decimals: 9,
    },
    USDC: {
      symbol: 'USDC',
      mint: new PublicKey('EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v'),
      decimals: 6,
    },
    USDT: {
      symbol: 'USDT',
      mint: new PublicKey('Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB'),
      decimals: 6,
    },
  },
};

// ─── PDA Seeds ────────────────────────────────────────────────────────────────

export const SEEDS = {
  // zk_shielded
  SHIELDED_POOL: 'shielded_pool',
  DENOMINATED_POOL: 'denominated_pool',
  MERKLE_TREE: 'merkle_tree',
  NULLIFIER: 'nullifier',
  NULLIFIER_SET: 'nullifier_set',
  NULLIFIER_BATCH: 'nullifier_batch',
  VK_DATA: 'vk_data',
  VK_DATA_SUBSCRIBER: 'vk_data_subscriber',
  SUBSCRIPTION_VAULT: 'subscription_vault',
  PRIVACY_ROUTE: 'privacy_route',
  AUCTION_ESCROW: 'auction_escrow',

  // relayer
  RELAYER_CONFIG: 'relayer_config',
  RELAYER: 'relayer',
  JOB: 'job',

  // registry
  REGISTRY: 'registry',

  // stark verifier
  PROOF_BUFFER: 'proof_buffer',
} as const;

// ─── Standard Denominations (in lamports/base units) ──────────────────────────

export const DENOMINATIONS = {
  SOL: [
    0.1 * 1e9,   // 0.1 SOL
    1 * 1e9,     // 1 SOL
    10 * 1e9,    // 10 SOL
    100 * 1e9,   // 100 SOL
  ],
  USDC: [
    10 * 1e6,    // $10
    100 * 1e6,   // $100
    1000 * 1e6,  // $1,000
    10000 * 1e6, // $10,000
  ],
  USDT: [
    10 * 1e6,
    100 * 1e6,
    1000 * 1e6,
    10000 * 1e6,
  ],
} as const;

// ─── Merkle Tree Config ───────────────────────────────────────────────────────

/**
 * Depth of the shielded-pool commitment tree.
 *
 * ⚠️ SOURCE OF TRUTH IS ON-CHAIN — DO NOT "ROUND UP" TO 20.
 *   - `programs/zk_shielded/src/state/pool_v3.rs` → `DEFAULT_TREE_DEPTH: u8 = 15`
 *   - `programs/p01_stark_verifier/src/verify.rs` → `CANONICAL_DEPTH: u64 = 15`,
 *     and the proof is REJECTED when the depth public input differs.
 *   - `programs/zk_shielded/src/instructions/subscribe_private_stark.rs`
 *     → `require!(tree_depth == 15, ...)`
 *   - `stark/src/air/merkle_path.rs` → `CANONICAL_DEPTH: usize = 15`
 *
 * No module of this package computes roots since 2.0.0 (the shield module
 * left); the constant stays as the published mirror of the on-chain depth.
 * A client that cascades the zero-hash chain any other number of levels gets a
 * root that can never match the chain, and the insert is rejected.
 */
export const MERKLE_TREE_DEPTH = 15;
export const MAX_LEAVES = 2 ** MERKLE_TREE_DEPTH; // 32,768
