use anchor_lang::prelude::*;

// =============================================================================
// V1 - Classical stealth payment (X25519 only)
// =============================================================================

/// StealthAccount - One-time stealth payment account (v1, classical)
///
/// This account represents a pending stealth payment that can only be claimed
/// by the intended recipient who possesses the corresponding private key.
/// The payment details are encrypted to preserve privacy.
///
/// Rent cost: ~114 bytes total => ~0.0016 SOL rent-exempt minimum
#[account]
#[derive(Default)]
pub struct StealthAccount {
    /// The derived stealth public key (one-time address)
    /// Generated using ECDH between sender and recipient viewing keys
    pub recipient_key: [u8; 32],

    /// Encrypted amount using recipient's viewing key
    /// Only the recipient can decrypt this to know the payment amount
    pub encrypted_amount: [u8; 32],

    /// Token mint address (Pubkey::default() for native SOL)
    pub token_mint: Pubkey,

    /// Whether this stealth payment has been claimed
    pub claimed: bool,

    /// Unix timestamp when the payment was created
    pub created_at: i64,

    /// PDA bump seed
    pub bump: u8,
}

impl StealthAccount {
    /// Account space calculation
    /// discriminator (8) + recipient_key (32) + encrypted_amount (32) +
    /// token_mint (32) + claimed (1) + created_at (8) + bump (1)
    pub const LEN: usize = 8 + 32 + 32 + 32 + 1 + 8 + 1;

    /// Seed prefix for PDA derivation
    pub const SEED_PREFIX: &'static [u8] = b"stealth";

    /// Stealth payment expiry time (30 days in seconds)
    pub const EXPIRY_SECONDS: i64 = 30 * 24 * 60 * 60;

    /// Initialize a new stealth payment
    pub fn initialize(
        &mut self,
        recipient_key: [u8; 32],
        encrypted_amount: [u8; 32],
        token_mint: Pubkey,
        created_at: i64,
        bump: u8,
    ) {
        self.recipient_key = recipient_key;
        self.encrypted_amount = encrypted_amount;
        self.token_mint = token_mint;
        self.claimed = false;
        self.created_at = created_at;
        self.bump = bump;
    }

    /// Mark the stealth payment as claimed
    pub fn mark_claimed(&mut self) {
        self.claimed = true;
    }

    /// Check if the payment has expired
    pub fn is_expired(&self, current_time: i64) -> bool {
        current_time > self.created_at.saturating_add(Self::EXPIRY_SECONDS)
    }

    /// Check if the payment can be claimed
    pub fn can_claim(&self, current_time: i64) -> bool {
        !self.claimed && !self.is_expired(current_time)
    }
}

// =============================================================================
// V2 - Hybrid stealth payment (X25519 + ML-KEM-768)
// =============================================================================

/// ML-KEM-768 ciphertext size per FIPS 203 (fixed, never changes)
pub const MLKEM768_CIPHERTEXT_LEN: usize = 1088;

/// StealthAccountV2 - Hybrid quantum-resistant stealth payment account
///
/// Extends the classical stealth payment with an ML-KEM-768 ciphertext so that
/// payment scanning remains secure even against a cryptographically relevant
/// quantum computer. The recipient uses both the X25519 ephemeral key AND the
/// KEM ciphertext to derive the shared secret.
///
/// # Account size breakdown
///   discriminator                 8
///   version                       1
///   ephemeral_pub_key            32   (X25519 ephemeral, used in both v1 & v2)
///   stealth_address              32   (Pubkey)
///   view_tag                      1   (quick-scan filter byte, 99.6% rejection)
///   amount                        8
///   token_mint                   32   (Pubkey)
///   slot                          8
///   claimed                       1
///   created_at                    8
///   bump                          1
///   kem_ciphertext             1088   (ML-KEM-768, fixed per FIPS 203)
///   ─────────────────────────────────
///   total                      1220 bytes
///
/// Rent cost: ~1220 bytes => ~0.0093 SOL rent-exempt minimum
/// (vs ~0.0016 SOL for v1 — the KEM ciphertext dominates the cost)
///
/// # Rent reclaim
/// The KEM ciphertext is only needed until the recipient decapsulates the
/// shared secret and claims the payment. The `close` attribute on the
/// claim instruction allows the recipient to close this account and reclaim
/// the ~0.0093 SOL rent deposit.
#[account]
pub struct StealthAccountV2 {
    /// Protocol version — always 2 for this account type
    pub version: u8,

    /// X25519 ephemeral public key generated by the sender.
    /// Used together with `kem_ciphertext` for hybrid key agreement.
    pub ephemeral_pub_key: [u8; 32],

    /// The one-time stealth address (Solana Pubkey) derived by the sender.
    /// The recipient scans for this using their viewing key + view_tag.
    pub stealth_address: Pubkey,

    /// Single-byte Diffie-Hellman view tag for fast scanning.
    /// Recipients compute view_tag from their viewing key and the ephemeral
    /// key; if it does not match, they skip this payment (99.6% rejection
    /// rate), avoiding expensive KEM decapsulation.
    pub view_tag: u8,

    /// Payment amount in token base units (lamports for SOL)
    pub amount: u64,

    /// Token mint address (Pubkey::default() for native SOL)
    pub token_mint: Pubkey,

    /// Solana slot at which this payment was recorded
    pub slot: u64,

    /// Whether this stealth payment has been claimed by the recipient
    pub claimed: bool,

    /// Unix timestamp when the payment was created
    pub created_at: i64,

    /// PDA bump seed
    pub bump: u8,

    /// ML-KEM-768 ciphertext (FIPS 203).
    /// Exactly 1088 bytes. The sender encapsulates against the recipient's
    /// ML-KEM public key; the recipient decapsulates to obtain a 32-byte
    /// shared secret that is combined with the X25519 shared secret to derive
    /// the stealth private key.
    pub kem_ciphertext: [u8; MLKEM768_CIPHERTEXT_LEN],
}

impl StealthAccountV2 {
    /// Account space calculation (see struct doc for breakdown)
    /// discriminator (8) + version (1) + ephemeral_pub_key (32) +
    /// stealth_address (32) + view_tag (1) + amount (8) + token_mint (32) +
    /// slot (8) + claimed (1) + created_at (8) + bump (1) +
    /// kem_ciphertext (1088)
    pub const LEN: usize = 8 + 1 + 32 + 32 + 1 + 8 + 32 + 8 + 1 + 8 + 1 + MLKEM768_CIPHERTEXT_LEN;

    /// Seed prefix for v2 stealth PDA derivation.
    /// Different from v1 ("stealth") to avoid collisions.
    pub const SEED_PREFIX: &'static [u8] = b"stealth_v2";

    /// Stealth payment expiry time (30 days in seconds)
    pub const EXPIRY_SECONDS: i64 = 30 * 24 * 60 * 60;

    /// Current protocol version
    pub const VERSION: u8 = 2;

    /// Initialize a new v2 hybrid stealth payment
    #[allow(clippy::too_many_arguments)]
    pub fn initialize(
        &mut self,
        ephemeral_pub_key: [u8; 32],
        stealth_address: Pubkey,
        view_tag: u8,
        amount: u64,
        token_mint: Pubkey,
        slot: u64,
        created_at: i64,
        bump: u8,
        kem_ciphertext: [u8; MLKEM768_CIPHERTEXT_LEN],
    ) {
        self.version = Self::VERSION;
        self.ephemeral_pub_key = ephemeral_pub_key;
        self.stealth_address = stealth_address;
        self.view_tag = view_tag;
        self.amount = amount;
        self.token_mint = token_mint;
        self.slot = slot;
        self.claimed = false;
        self.created_at = created_at;
        self.bump = bump;
        self.kem_ciphertext = kem_ciphertext;
    }

    /// Mark the stealth payment as claimed
    pub fn mark_claimed(&mut self) {
        self.claimed = true;
    }

    /// Check if the payment has expired
    pub fn is_expired(&self, current_time: i64) -> bool {
        current_time > self.created_at.saturating_add(Self::EXPIRY_SECONDS)
    }

    /// Check if the payment can be claimed
    pub fn can_claim(&self, current_time: i64) -> bool {
        !self.claimed && !self.is_expired(current_time)
    }
}

// =============================================================================
// Anchor Events — clients subscribe via connection.onLogs()
// =============================================================================

/// Emitted when a v1 (classical) stealth payment is created.
/// Clients index these events to find incoming payments without any server.
#[event]
pub struct StealthPaymentCreated {
    /// Protocol version (always 1 for this event)
    pub version: u8,
    /// Stealth address (one-time recipient address)
    pub stealth_address: [u8; 32],
    /// Token mint
    pub token_mint: Pubkey,
    /// Payment amount
    pub amount: u64,
    /// Block slot
    pub slot: u64,
}

/// Emitted when a v2 (hybrid quantum-resistant) stealth payment is created.
///
/// Contains all fields needed for the recipient to:
/// 1. Check view_tag for quick rejection (99.6% filter)
/// 2. Perform X25519 ECDH with ephemeral_pub_key
/// 3. Perform ML-KEM-768 decapsulation on kem_ciphertext
/// 4. Combine both shared secrets to derive the stealth private key
///
/// Clients subscribe to these events with `connection.onLogs()` to find
/// payments without any relayer or server.
#[event]
pub struct StealthPaymentCreatedV2 {
    /// Protocol version (always 2 for this event)
    pub version: u8,
    /// X25519 ephemeral public key
    pub ephemeral_pub_key: [u8; 32],
    /// Derived one-time stealth address
    pub stealth_address: Pubkey,
    /// View tag for quick scanning (single byte)
    pub view_tag: u8,
    /// Payment amount in base token units
    pub amount: u64,
    /// Token mint address
    pub token_mint: Pubkey,
    /// Block slot
    pub slot: u64,
    /// ML-KEM-768 ciphertext (1088 bytes)
    pub kem_ciphertext: Vec<u8>,
}

/// Emitted when a stealth payment (v1 or v2) is claimed by the recipient.
/// The `rent_reclaimed` field indicates whether the account was closed and
/// rent returned to the claimer.
#[event]
pub struct StealthPaymentClaimed {
    /// Protocol version of the claimed payment
    pub version: u8,
    /// The stealth address that was claimed
    pub stealth_address: Pubkey,
    /// Claimer's wallet address
    pub claimer: Pubkey,
    /// Amount claimed
    pub amount: u64,
    /// Whether the announcement account was closed (rent reclaimed)
    pub rent_reclaimed: bool,
}

/// Decoy levels for transaction privacy
/// Higher levels provide more privacy but cost more compute units
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy, PartialEq, Eq)]
pub enum DecoyLevel {
    /// No decoys (fastest, least private)
    None = 0,
    /// 2 decoy outputs
    Low = 1,
    /// 4 decoy outputs
    Medium = 2,
    /// 8 decoy outputs
    High = 3,
    /// 16 decoy outputs (most private, highest cost)
    Maximum = 4,
}

impl Default for DecoyLevel {
    fn default() -> Self {
        DecoyLevel::Medium
    }
}

impl DecoyLevel {
    /// Convert from u8 to DecoyLevel
    pub fn from_u8(value: u8) -> Option<Self> {
        match value {
            0 => Some(DecoyLevel::None),
            1 => Some(DecoyLevel::Low),
            2 => Some(DecoyLevel::Medium),
            3 => Some(DecoyLevel::High),
            4 => Some(DecoyLevel::Maximum),
            _ => None,
        }
    }

    /// Get the number of decoys for this level
    pub fn decoy_count(&self) -> u8 {
        match self {
            DecoyLevel::None => 0,
            DecoyLevel::Low => 2,
            DecoyLevel::Medium => 4,
            DecoyLevel::High => 8,
            DecoyLevel::Maximum => 16,
        }
    }
}
