//! Goldilocks Poseidon (t = 3), for the pool program.
//!
//! # Why this file exists
//!
//! Before it, `zk_shielded` could not hash ANYTHING in the field its own tree
//! is built in. `state/merkle_tree.rs::hash_pair` panics, and its
//! commented-out body is BN254 -- the wrong field entirely. The v3 denominated
//! tree works only because the client supplies the root
//! (`insert_with_root`), so the program never had to hash.
//!
//! Circuit 7 ends that. Its public input 1 is a depth-12 SUBTREE root, not the
//! pool root, so a C7 proof on its own says "this leaf is in SOME subtree".
//! Anyone holding a leaf in any subtree satisfies it. The spending instruction
//! has to walk the remaining levels itself, against caller-supplied siblings,
//! and bind the result with `is_valid_root` -- and to do that it has to hash.
//!
//! # ⛔ Why it is a copy, and how the copy is kept honest
//!
//! The reference is `stark/src/poseidon`, which the AIR, the prover and the
//! client all share. This program CANNOT depend on it: that crate pulls in
//! winterfell, a host dependency that does not belong in a BPF program.
//!
//! So the constants below are a copy -- and a hand-transcribed copy of ninety
//! field constants is exactly the silent divergence this repo has been bitten
//! by before. They are GENERATED by
//! `p01-stark`'s `emit_poseidon_gl_for_zk_shielded` (`#[ignore]`d, run by
//! hand), and `parity_vectors_match_the_reference_implementation` below pins
//! eight input/output triples produced by that same reference. If the two ever
//! diverge, that test goes red -- it does not need the reference in scope to
//! notice, which is the whole point.
//!
//! # Parameters
//!
//! t = 3 (rate 2, capacity 1), 30 FULL rounds, S-box x^7, circulant MDS
//! [[3,1,1],[1,3,1],[1,1,3]]. Full rounds everywhere -- not the usual
//! full/partial split -- because that is what the AIR's constraint structure
//! encodes, and the on-chain hash must agree with the circuit, not with the
//! Poseidon paper.

/// Goldilocks prime: 2^64 - 2^32 + 1.
pub const MODULUS: u64 = 0xFFFF_FFFF_0000_0001;

/// Round constants, three per round for thirty rounds.
///
/// ⛔ GENERATED. Do not edit by hand -- re-run the emitter in `p01-stark`.
#[rustfmt::skip]
const RC_T3: [u64; 90] = [
    0xA98E4673F9036E0B, 0x3DB4A488E825C32A, 0x60DE653E0ED43E20, // round 0
    0x8B4F0D2B6EA19313, 0x2F97E83E60E2C4DD, 0xACEA6E9AF6C2C725, // round 1
    0xD5604EEF12E3CABC, 0x1EB9DB12A1E71B79, 0x7AD5966D3A790D0D, // round 2
    0xBFAE604E2C72E1D9, 0x5FA21F2143C2F72A, 0xC3AE00CF4D83D5B8, // round 3
    0x9E8D1423CD728E2F, 0x45D8E40E789C13AB, 0x6B9E0D183D0B0E71, // round 4
    0x8A15B14C28D50C0A, 0xD1EEF5AFE2C45C82, 0x3C914BFFF61CC9D3, // round 5
    0xF7D2A1F9AB51E8C4, 0x2E4D3B16C89F0A55, 0xB8F0E1D7A3C24B96, // round 6
    0x5169E0D4F3812C47, 0x0AF31E8BC2D57698, 0x94B6E123D8F40C49, // round 7
    0xE2C9F5670AB18D3A, 0x7B30E894F1D26C0B, 0x14A3D7C6E810FB5C, // round 8
    0xAD76E0B1F934CA0D, 0x46D9E3825C01A9BE, 0xE01C67DA3F24586F, // round 9
    0x799FE120D347B680, 0x12028BCDA6F0E531, 0xAB45C7FEB9132482, // round 10
    0x4468E041DC360373, 0xDD8BF16E0F590264, 0x76AEE291325C0155, // round 11
    0x0FD1D3B465BF0046, 0xA804E4C798020F37, 0x4127F5EA0B256E28, // round 12
    0xDA4AE60D3E480D19, 0x736DD73071BB4C0A, 0x0C90C8439EDE8AFB, // round 13
    0xA5C3D966D2019BEC, 0x3EF6EA89050490DD, 0xD829FB0C382B5FCE, // round 14
    0x715D0C2F6B4E7EBF, 0x0A801D528A719DB0, 0xA3B32E75BDB4BCA1, // round 15
    0x3CE63F98F0D7DB92, 0xD6194ABD2400FA83, 0x6F4C5BE057241974, // round 16
    0x087F6CE38A473865, 0xA1A27E06BD6A5756, 0x3AD58F29F08D7647, // round 17
    0xD408A04D239067B8, 0x6D3BB170568340A9, 0x066ED293899C5F9A, // round 18
    0x9FA1E3B6BCBF7E8B, 0x38D4F4D9EFE29D7C, 0xD20805FD13057C6D, // round 19
    0x6B3B17202A282B5E, 0x046E2843540B4A4F, 0x9DA13966872E6940, // round 20
    0x36D44A89BA516831, 0xCF075BACFD745722, 0x683A6CD020574613, // round 21
    0x016D7DF353BA3504, 0x9AA08F1686DD13F5, 0x33D3A039B90032E6, // round 22
    0xCD06B15CEC6351D7, 0x6639C28019A670C8, 0xFF6CD3A34CC94FB9, // round 23
    0x989FE4C67FEC6EAA, 0x31D2F5E9B30F4D9B, 0xCB060D0CE6326C8C, // round 24
    0x6439180FE231AB7D, 0xFD6C29261546CA6E, 0x969F3A84487BE95F, // round 25
    0x2FD24AC7B8C50850, 0xC90555EAEB981741, 0x62386B17DE5C3632, // round 26
    0xFB5B7448E86C4523, 0x94AE8524217F3414, 0x2DD19647549A2305, // round 27
    0xC6F4A76A879D01F6, 0x5F17B18DBAC0E0E7, 0xF83ACBB0EDE3BFD8, // round 28
    0x915DDC43210C9EC9, 0x2A80ED66544FBDBA, 0xC3A3FE8987B2BCAB, // round 29
];

/// Eight `(a, b, poseidon_hash2(a, b))` triples from the reference
/// implementation. ⛔ GENERATED alongside the constants above.
#[cfg(test)]
#[rustfmt::skip]
const PARITY_HASH2: [(u64, u64, u64); 8] = [
    (0x0000000000000000, 0x0000000000000000, 0xFA84A507BF928A6F),
    (0x0000000000000001, 0x0000000000000000, 0x34F22A9E8D0F8DE0),
    (0x0000000000000000, 0x0000000000000001, 0x2A0591A3FABCF259),
    (0x0000000000000001, 0x0000000000000002, 0xFC5B6499D437E945),
    (0xFFFFFFFF00000000, 0x0000000000000001, 0xEC9D7BB0753F5CD3),
    (0x000000000000002A, 0x00000000000003E7, 0x1950591D9EC0675E),
    (0x0123456789ABCDEF, 0xFEDCBA9876543210, 0x6A67B3C959AD6A6D),
    (0xFFFFFFFF00000000, 0xFFFFFFFF00000000, 0x4039F5851BD0CFDB),
];

#[inline(always)]
fn add(a: u64, b: u64) -> u64 {
    let (s, carry) = a.overflowing_add(b);
    // Goldilocks: 2^64 = 2^32 - 1 (mod p), so a carry folds back as +0xFFFFFFFF.
    let s = s.wrapping_add((carry as u64) * 0xFFFF_FFFF);
    if s >= MODULUS {
        s - MODULUS
    } else {
        s
    }
}

#[inline(always)]
fn reduce128(x: u128) -> u64 {
    // p = 2^64 - 2^32 + 1, so 2^64 = 2^32 - 1 and 2^96 = -1 (mod p).
    // Standard Goldilocks folding, written out rather than looped so the BPF
    // cost is a fixed handful of instructions.
    let lo = x as u64;
    let hi = (x >> 64) as u64;
    let hi_lo = hi as u32 as u64;
    let hi_hi = hi >> 32;

    let (a, borrow) = lo.overflowing_sub(hi_hi);
    let a = a.wrapping_sub((borrow as u64) * 0xFFFF_FFFF);

    let b = hi_lo.wrapping_mul(0xFFFF_FFFF);

    add(a % MODULUS, b % MODULUS)
}

#[inline(always)]
fn mul(a: u64, b: u64) -> u64 {
    reduce128((a as u128) * (b as u128))
}

/// x^7, the S-box. Four multiplications.
#[inline(always)]
fn pow7(x: u64) -> u64 {
    let x2 = mul(x, x);
    let x4 = mul(x2, x2);
    mul(mul(x4, x2), x)
}

/// MDS multiply for the circulant [[3,1,1],[1,3,1],[1,1,3]].
///
/// `out_i = 3*s_i + s_j + s_k = (s0 + s1 + s2) + 2*s_i`, so the whole matrix
/// costs one sum and three doublings -- not nine multiplications. The circulant
/// shape is asserted on the reference side by the emitter, so this shortcut
/// cannot silently stop matching the AIR.
#[inline(always)]
fn mds(state: &mut [u64; 3]) {
    let sum = add(add(state[0], state[1]), state[2]);
    for s in state.iter_mut() {
        *s = add(sum, add(*s, *s));
    }
}

/// The t=3 permutation: 30 full rounds of (add constants, x^7 on all three,
/// MDS).
pub fn permutation_t3(state: &mut [u64; 3]) {
    for round in 0..30 {
        for i in 0..3 {
            state[i] = add(state[i], RC_T3[round * 3 + i]);
        }
        for s in state.iter_mut() {
            *s = pow7(*s);
        }
        mds(state);
    }
}

/// `Poseidon(a, b)` with rate 2: capacity starts at zero, output is lane 0.
///
/// This is the pool tree's node hash. `left` and `right` must already be
/// canonical Goldilocks values (`< MODULUS`); callers reading them out of a
/// 32-byte leaf take the low 8 bytes little-endian, which is how the v3 tree
/// stores them.
pub fn hash2(a: u64, b: u64) -> u64 {
    let mut state = [a % MODULUS, b % MODULUS, 0u64];
    permutation_t3(&mut state);
    state[0]
}

#[cfg(test)]
mod tests {
    use super::*;

    /// 🚨 THE TEST THIS FILE EXISTS FOR.
    ///
    /// The constants above are a copy of `stark/src/poseidon`, and this program
    /// cannot depend on the crate that owns the original. Without this pin the
    /// two could drift and NOTHING would notice until an on-chain root stopped
    /// matching a proof -- which surfaces as an unspendable note, not as an
    /// error.
    #[test]
    fn parity_vectors_match_the_reference_implementation() {
        for (a, b, want) in PARITY_HASH2.iter() {
            assert_eq!(
                hash2(*a, *b),
                *want,
                "poseidon_gl diverged from stark/src/poseidon on ({a:#x}, {b:#x})",
            );
        }
    }

    /// The field arithmetic itself, against u128 done the slow way.
    #[test]
    fn field_ops_agree_with_u128_arithmetic() {
        let cases: [u64; 9] = [
            0,
            1,
            2,
            MODULUS - 1,
            MODULUS - 2,
            0xFFFF_FFFF_0000_0000,
            0x0123_4567_89AB_CDEF,
            0xFEDC_BA98_7654_3210 % MODULUS,
            0x8000_0000_0000_0000 % MODULUS,
        ];
        let p = MODULUS as u128;
        for a in cases.iter() {
            for b in cases.iter() {
                assert_eq!(add(*a, *b) as u128, (*a as u128 + *b as u128) % p, "add");
                assert_eq!(mul(*a, *b) as u128, (*a as u128 * *b as u128) % p, "mul");
            }
            let want = (0..7).fold(1u128, |acc, _| acc * (*a as u128) % p);
            assert_eq!(pow7(*a) as u128, want, "pow7 at {a:#x}");
        }
    }

    /// The circulant shortcut equals the full 3x3 product.
    #[test]
    fn the_mds_shortcut_equals_the_full_matrix() {
        const M: [[u64; 3]; 3] = [[3, 1, 1], [1, 3, 1], [1, 1, 3]];
        for seed in 0..32u64 {
            let s = [
                seed.wrapping_mul(0x9E37_79B9_7F4A_7C15) % MODULUS,
                seed.wrapping_mul(0x2545_F491_4F6C_DD1D) % MODULUS,
                seed.wrapping_mul(0xD1B5_4A32_D192_ED03) % MODULUS,
            ];
            let mut fast = s;
            mds(&mut fast);
            let mut slow = [0u64; 3];
            for i in 0..3 {
                let mut acc = 0u64;
                for j in 0..3 {
                    acc = add(acc, mul(M[i][j], s[j]));
                }
                slow[i] = acc;
            }
            assert_eq!(fast, slow, "MDS shortcut diverged at seed {seed}");
        }
    }
}
