/**
 * What the zkspl-sdk README says the p01_zkspl program enforces. Audit v1,
 * finding F46 (SDK/README part).
 *
 * The README announced "balance proofs prove balance >= threshold" and
 * withdrawals whose "proof validates the balance update", and listed devnet as
 * "Live. Programs deployed and verified." None of it holds:
 *
 *   - the program's `prove_balance` checks commitment integrity only; the
 *     threshold is emitted in the event but no constraint binds it
 *     (programs/p01_zkspl/src/instructions/prove_balance.rs:19-24);
 *   - `withdraw` forces amount_hash = Poseidon(0, 0), so the proof never binds
 *     the public amount to the balance change: any amount can be withdrawn
 *     from the vault (withdraw.rs);
 *   - the program id this SDK declares is not deployed on devnet (root README,
 *     "their declared IDs are not deployed on devnet").
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const README = readFileSync(resolve(__dirname, '..', 'README.md'), 'utf8');
const CONSTANTS = readFileSync(resolve(__dirname, 'constants.ts'), 'utf8');

describe('zkspl-sdk README: no claim the program does not enforce (F46)', () => {
  it('says the threshold of a balance proof is not enforced', () => {
    expect(README).toMatch(/threshold[^\n]{0,200}not enforced/i);
  });

  it('says a withdrawal amount is not bound to the balance (conservation not enforced)', () => {
    expect(README).toMatch(/(conservation|withdraw)[^\n]{0,300}not (enforced|bound)/i);
  });

  it('does not list devnet as live and deployed', () => {
    expect(README).not.toMatch(/Programs deployed and verified/i);
    const row = README.split('\n').find((l) => /^\|\s*`devnet`/.test(l));
    expect(row, 'no devnet row').toBeDefined();
    expect(row!).toMatch(/Not deployed/i);
  });

  // The zkspl id sits inside the block that scripts/sync-program-ids.ts owns.
  // A hand edit there is drift (`sync-program-ids --check` fails) and the next
  // `--write` erases it. So the block must be exactly what the generator
  // emits, and the not-deployed disclosure must live outside the sentinels,
  // where it survives regeneration.
  const OPEN = '// <auto-generated-program-ids>';
  const CLOSE = '// </auto-generated-program-ids>';
  const GENERATOR = readFileSync(
    resolve(__dirname, '..', '..', '..', 'scripts', 'sync-program-ids.ts'),
    'utf8',
  );
  const generatedZksplDoc = (() => {
    const fn = GENERATOR.slice(GENERATOR.indexOf('function zksplSdkBlock'));
    const m = fn.match(/lines\.push\('([^']*)'\);\s*\n\s*lines\.push\(`export const ZKSPL_PROGRAM_ID/);
    return m ? m[1] : undefined;
  })();

  it('the generated block carries the generator\'s own JSDoc for ZKSPL_PROGRAM_ID (no hand edit between the sentinels)', () => {
    expect(generatedZksplDoc, 'cannot find the zkspl JSDoc line in zksplSdkBlock()').toBeDefined();
    const block = CONSTANTS.slice(CONSTANTS.indexOf(OPEN) + OPEN.length, CONSTANTS.indexOf(CLOSE));
    const beforeId = block.slice(0, block.indexOf('export const ZKSPL_PROGRAM_ID')).trim();
    expect(beforeId).toBe(generatedZksplDoc);
  });

  it('constants.ts discloses, outside the sentinels, that the zkspl program id is not deployed', () => {
    const outside = CONSTANTS.slice(0, CONSTANTS.indexOf(OPEN));
    expect(outside).toMatch(/ZKSPL_PROGRAM_ID[\s\S]{0,200}NOT deployed on devnet or mainnet/);
    if (/Deployed/.test(generatedZksplDoc ?? '')) {
      // Until the generator's line is fixed, the disclosure names it as stale.
      expect(outside).toMatch(/Deployed p01_zkspl program ID \(devnet\)[\s\S]{0,200}(stale|false|wrong)/i);
    }
  });
});
