import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

/**
 * THE CLIENT ENCODER AND THE PROGRAM'S ARGUMENT LIST MUST AGREE, BYTE FOR BYTE.
 *
 * Mirror of `apps/extension/src/shared/services/instruction-encoding.test.ts`.
 * The two clients hand-roll the same Borsh layout independently, which is
 * exactly why both need pinning: a fix applied to one is not a fix.
 *
 * `subscribe_private_stark` lost its `client_stealth_meta: Option<[u8;64]>`
 * argument, which sat between `stark_commitment` and `license_commitment`. This
 * encoder wrote that Option's 1-byte tag EVEN WHEN NONE. Leaving the byte in
 * place fails silently, not loudly: the program reads `license_commitment`'s
 * tag from the stale meta tag (0 = None) and drops the license commitment, so
 * every vault this client creates has no license key and nothing reports it.
 *
 * `claim_period` stopped declaring `retailer` as a `Signer`. Keeping
 * `isSigner: true` here makes the RUNTIME reject the transaction for a missing
 * signature before the program runs — failing precisely for the merchants the
 * permissionless change exists to rescue, whose retailer key no longer exists.
 *
 * Both builders are module-private, so this reads the IDL — the program's own
 * generated description, regenerated by `anchor idl build` and therefore unable
 * to drift from the Rust — and checks the encoder source against it.
 */

// vitest runs with cwd = apps/mobile.
const REPO_ROOT = resolve(process.cwd(), '../..');

interface IdlArg {
  name: string;
  type: unknown;
}
interface IdlAccount {
  name: string;
  signer?: boolean;
  writable?: boolean;
}
interface IdlInstruction {
  name: string;
  args: IdlArg[];
  accounts: IdlAccount[];
}

const idl = JSON.parse(
  readFileSync(resolve(REPO_ROOT, 'target/idl/zk_shielded.json'), 'utf8'),
) as { instructions: IdlInstruction[] };

const instruction = (name: string): IdlInstruction => {
  const ix = idl.instructions.find((i) => i.name === name);
  if (!ix) throw new Error(`no ${name} in the IDL — the instruction was renamed or removed`);
  return ix;
};

/**
 * Borsh byte length of an IDL type, with every `Option` absent (tag only).
 *
 * \u26a0 RETURNS null FOR A VARIABLE-LENGTH TYPE, and that is the whole reason
 * this function changed. `subscribe_private_stark` gained the subtree walk --
 * `siblings: vec<u64>` and `directions: bytes` -- so the instruction no longer
 * HAS one length. A size table that threw on them was right to refuse rather
 * than invent a number; what it could not do is say which part is fixed.
 */
function borshLenWithOptionsNone(type: unknown): number | null {
  if (type === 'u64' || type === 'i64') return 8;
  if (type === 'u8' || type === 'bool') return 1;
  if (type === 'pubkey') return 32;
  if (type === 'bytes' || type === 'string') return null;
  if (typeof type === 'object' && type !== null) {
    const t = type as Record<string, unknown>;
    if ('option' in t) return 1;
    if ('vec' in t) return null;
    if (Array.isArray(t.array)) return Number(t.array[1]);
  }
  throw new Error(`unhandled IDL type in the size table: ${JSON.stringify(type)}`);
}

const source = readFileSync(
  resolve(process.cwd(), 'services/subscriptionVault/index.ts'),
  'utf8',
);

/**
 * The numeric literals of a `Buffer.alloc(...)` expression, summed, plus one
 * per named term — the named terms are Option sizes and an absent Option is a
 * single tag byte.
 */
function allocatedBytesWithOptionsNone(fnName: string): number {
  const at = source.indexOf(`function ${fnName}(`);
  expect(at, `${fnName} is gone from services/subscriptionVault/index.ts`).toBeGreaterThan(-1);
  const allocAt = source.indexOf('Buffer.alloc(', at);
  expect(allocAt, `${fnName} no longer allocates its instruction data`).toBeGreaterThan(-1);
  const open = allocAt + 'Buffer.alloc('.length;
  const close = source.indexOf(')', open);
  const terms = source
    .slice(open, close)
    .split('+')
    .map((t) => t.trim());
  return terms.reduce((sum, term) => sum + (/^\d+$/.test(term) ? Number(term) : 1), 0);
}

describe('subscribe_private_stark — hand-rolled Borsh vs the program IDL', () => {
  it('no longer sends client_stealth_meta, on either side', () => {
    expect(instruction('subscribe_private_stark').args.map((a) => a.name)).not.toContain(
      'client_stealth_meta',
    );
    // The DECODER keeps reading the field: the account layout is unchanged and
    // the vaults already on devnet still carry whatever was written to them.
    // What must be gone is the encoder's parameter and its option size.
    expect(source).not.toContain('metaOptionSize');
    const buildAt = source.indexOf('function buildSubscribePrivateStarkIx(');
    expect(buildAt).toBeGreaterThan(-1);
    const builder = source.slice(buildAt, source.indexOf('\n}', buildAt));
    expect(builder).not.toContain('clientStealthMeta');
  });

  it('allocates exactly the FIXED bytes the program will deserialise', () => {
    // The variable tail is checked separately below: `allocatedBytesWithOptionsNone`
    // sums the numeric literals of the `Buffer.alloc(...)` and counts one per
    // named term, and the walk arrives as exactly one named term (`walkBytes`).
    const ix = instruction('subscribe_private_stark');
    const names = ix.args.map((a) => a.name);
    // ⚠ THE WALK BEGINS AT `subtree_root`, NOT AT THE FIRST VARIABLE ARG.
    // The builder folds the root's eight bytes into its `walkBytes` term
    // together with the two length-prefixed arrays, so the boundary that
    // matters here is the encoder's, not Borsh's. Getting it wrong is an
    // eight-byte discrepancy that reads like a missing field.
    const walkAt = names.indexOf('subtree_root');
    expect(walkAt, 'the subtree walk is no longer in this instruction').toBeGreaterThan(-1);
    const lens = ix.args.map((a) => borshLenWithOptionsNone(a.type));
    expect(
      lens.slice(walkAt).some((l) => l === null),
      'nothing after subtree_root is variable-length any more',
    ).toBe(true);
    const fixed = lens.slice(0, walkAt).reduce<number>((sum, l) => sum + (l ?? 0), 0);
    // discriminator + the individually written args + the one `walkBytes` term
    expect(allocatedBytesWithOptionsNone('buildSubscribePrivateStarkIx')).toBe(8 + fixed + 1);
  });

  it('sizes the subtree walk from the arrays themselves, not from a constant', () => {
    // \U0001f6a8 A CONSTANT HERE WOULD TRUNCATE A DEEPER TREE and the failure
    // would arrive on chain, after the proof was uploaded and paid for.
    const buildAt = source.indexOf('function buildSubscribePrivateStarkIx(');
    const builder = source.slice(buildAt, source.indexOf('\n}', buildAt));
    expect(builder).toMatch(/siblings\.length \* 8/);
    expect(builder).toMatch(/directions\.length/);
  });

  it('puts license_commitment BEFORE the walk, so a stray tag byte is no longer silent', () => {
    // \u26a0 THE PROPERTY INVERTED, AND IT INVERTED IN OUR FAVOUR. This case
    // asserted `license_commitment` was LAST, because a mis-encoded Option tag
    // at the very end is absorbed silently. The instruction then gained
    // `subtree_root`, `siblings` and `directions`, so a stray tag now shifts the
    // whole walk and the program rejects it instead of accepting a subscription
    // bound to nothing. What must hold is the ORDER, since the encoder is
    // hand-rolled and Borsh is positional.
    const names = instruction('subscribe_private_stark').args.map((a) => a.name);
    expect(names).toEqual([
      'nullifier',
      'merkle_root',
      'min_epoch',
      'subscriber_commitment',
      'rate',
      'interval_slots',
      'vk_hash_subscriber',
      'stark_commitment',
      'license_commitment',
      'subtree_root',
      'siblings',
      'directions',
    ]);
  });
});

describe('claim_period — the permissionless account shape', () => {
  it('is not a signer in the IDL', () => {
    const retailer = instruction('claim_period').accounts.find((a) => a.name === 'retailer');
    expect(retailer, 'claim_period no longer declares a retailer account').toBeDefined();
    expect(retailer!.signer ?? false).toBe(false);
    expect(retailer!.writable).toBe(true);
  });

  it('is not marked a signer by the client either', () => {
    const at = source.indexOf('function buildClaimPeriodIx(');
    expect(at, 'buildClaimPeriodIx is gone').toBeGreaterThan(-1);
    const keysAt = source.indexOf('const keys = [', at);
    const firstKey = source.slice(keysAt, source.indexOf(']', keysAt));
    expect(firstKey).toContain('{ pubkey: retailer, isSigner: false, isWritable: true }');
  });

  it('reads the retailer off the vault instead of assuming the local wallet', () => {
    // The old code passed the local wallet as the retailer AND as the signer,
    // so claiming only ever worked if you happened to be the merchant. With a
    // non-signing account the same code would name the WRONG payee and the
    // program would reject it with Unauthorized.
    const at = source.indexOf('export async function claimPeriod(');
    expect(at).toBeGreaterThan(-1);
    const body = source.slice(at, source.indexOf('\n}', at));
    expect(body).toContain('buildClaimPeriodIx(new PublicKey(vault.retailer)');
    expect(body).not.toContain('buildClaimPeriodIx(walletPubkey');
  });
});
