/**
 * Constants for the ZK shielded system (STARK / Goldilocks edition).
 *
 * BREAKING CHANGE in v1.0.0: switched from BN254 + Groth16 to Goldilocks +
 * STARK. All field arithmetic now happens mod `0xFFFFFFFF00000001` (i.e.
 * `2^64 - 2^32 + 1`). On-chain commitments / nullifiers / merkle leaves pack
 * into the low 8 bytes of a 32-byte LE buffer (bytes 8..32 are zero).
 */

/**
 * Goldilocks field modulus: p = 2^64 - 2^32 + 1.
 * Same modulus used by `@protocol-01/stark-prover`, the STARK verifier
 * program, and the privacy-sdk Goldilocks-Poseidon helpers.
 */
export const FIELD_MODULUS = 0xFFFFFFFF00000001n;

/**
 * Default Merkle tree depth for STARK circuits (matches circuit 6 / merkle
 * paths used by the on-chain `zk_shielded` program). The previous Groth16
 * tree was depth 20; the STARK tree is depth 15 to keep prover memory in
 * check while still supporting 32 768 notes per pool.
 */
export const MERKLE_TREE_DEPTH = 15;

/**
 * Maximum tree leaves at depth 15.
 */
export const MAX_TREE_LEAVES = 2 ** MERKLE_TREE_DEPTH;

/**
 * Zero value for empty Merkle tree leaves under Goldilocks-Poseidon.
 * The cascade is `Z[0] = 0`, `Z[i] = hash2(Z[i-1], Z[i-1])`. This constant
 * is `Z[0]` — callers needing intermediate zeros at higher levels should
 * compute the cascade via the helpers in `@protocol-01/privacy-sdk` or
 * mirror the Goldilocks zero cascade locally.
 */
export const ZERO_VALUE = 0n;

/**
 * STARK circuit IDs. Mirrors `STARK_CIRCUITS` from
 * `@protocol-01/stark-prover` and `@protocol-01/privacy-sdk` so callers
 * importing from this SDK don't need to depend on either to discover the
 * circuit IDs.
 */
export const STARK_CIRCUITS = {
  SUBSCRIBER_OWNERSHIP: 0,
  POOL_COMMITMENT: 1,
  BALANCE_PROOF: 2,
  MERKLE_PATH: 3,
  CONFIDENTIAL_BALANCE: 4,
  TRANSFER: 5,
  /**
   * Variable-pool merkle update proof. NOT yet exported by the bundled WASM
   * — calls to `STARK_CIRCUITS.MERKLE_UPDATE` will throw at runtime until
   * the WASM is rebuilt. Once available, no migration is required.
   */
  MERKLE_UPDATE: 6,
} as const;

/**
 * Network type for program configuration
 */
export type NetworkId = 'devnet' | 'mainnet-beta' | 'localnet';

// <auto-generated-program-ids>
// DO NOT EDIT BY HAND. Run `pnpm sync-program-ids` from repo root to regenerate.
// Source of truth: D:\Protocol-01\Anchor.toml

/**
 * Program IDs by network. Synced from Anchor.toml.
 */
export const PROGRAM_IDS: Record<NetworkId, string> = {
  'devnet': '2w4WRvujjrZYip1dUrp3X4nzoPVWeRZF9KnjtvSstGms',
  'mainnet-beta': '8dK17NxQUFPWsLg7eJphiCjSyVfBk2ywC5GU6ctK4qrY',
  'localnet': 'GbVM5yvetrSD194Hnn1BXnR56F8ZWNKnij7DoVP9j27c',
};

/**
 * Program ID for the ZK shielded pool (devnet default).
 */
export const ZK_SHIELDED_PROGRAM_ID = PROGRAM_IDS.devnet;
// </auto-generated-program-ids>

/**
 * STARK verifier program ID (`p01_stark_verifier`). Re-exported from
 * `@protocol-01/stark-prover` would create a circular dep at the sub-path
 * level, so we mirror the on-chain devnet ID here. Callers can override
 * via `ShieldedClientConfig.starkVerifierProgramId`.
 */
export const STARK_VERIFIER_PROGRAM_ID = '5tBhkRLP2DV6szRFAiZJ6agJqZSMfWQbsy3FjybEHDBe';

/**
 * Get the program ID for the given network.
 * Falls back to devnet if no network is specified.
 */
export function getProgramId(network?: string): string {
  const net = (network ?? 'devnet') as NetworkId;
  const id = PROGRAM_IDS[net];

  if (id === undefined) {
    throw new Error(
      `getProgramId: unknown network '${net}'. Expected one of: devnet, mainnet-beta, localnet.`
    );
  }

  if (id === '') {
    throw new Error(
      `getProgramId: the ZK shielded program is not yet deployed on '${net}'. ` +
      `Pass a custom programId in your ShieldedClientConfig, or use 'devnet' or 'localnet' for testing.`
    );
  }

  return id;
}

/**
 * Seed prefixes for PDA derivation
 */
export const PDA_SEEDS = {
  SHIELDED_POOL: Buffer.from('shielded_pool'),
  MERKLE_TREE: Buffer.from('merkle_tree'),
  NULLIFIER_SET: Buffer.from('nullifier_set'),
  NULLIFIER_BATCH: Buffer.from('nullifier_batch'),
  NULLIFIER: Buffer.from('nullifier'),
  VK_DATA: Buffer.from('vk_data'),
} as const;

/**
 * Anchor instruction discriminators for the STARK instruction family
 * (`shield_stark` / `transfer_stark` / `unshield_stark`). Byte values match
 * `packages/privacy-sdk/src/modules/shield.ts` and the on-chain handlers in
 * `programs/zk_shielded`. Any drift breaks every shielded transaction.
 */
export const IX_DISCRIMINATORS = {
  SHIELD_STARK:   Buffer.from([241, 184, 171, 177, 138,  30, 238, 145]),
  TRANSFER_STARK: Buffer.from([101,  77, 136,  73,  63, 103, 214, 251]),
  UNSHIELD_STARK: Buffer.from([189,  84, 110, 154, 217, 120, 183, 239]),
} as const;

/**
 * Encryption constants
 */
export const ENCRYPTION = {
  /** XChaCha20-Poly1305 nonce size */
  NONCE_SIZE: 24,
  /** Encrypted note overhead (nonce + tag) */
  OVERHEAD: 40,
  /** Key size */
  KEY_SIZE: 32,
} as const;

/**
 * Default relayer fee in basis points (0.1%)
 */
export const DEFAULT_RELAYER_FEE_BPS = 10;

/**
 * Maximum relayer fee in basis points (1%)
 */
export const MAX_RELAYER_FEE_BPS = 100;

/**
 * Number of historical roots to keep
 */
export const MAX_HISTORICAL_ROOTS = 100;

/**
 * Proof generation timeout (ms)
 */
export const PROOF_GENERATION_TIMEOUT = 120000; // 2 minutes
