import { create } from 'zustand';
import { persist, createJSONStorage } from 'zustand/middleware';
import AsyncStorage from '@react-native-async-storage/async-storage';
import * as SecureStore from 'expo-secure-store';
import { PublicKey } from '@solana/web3.js';
import { poseidon2 } from 'poseidon-lite';
import { getConnection } from '../services/solana/connection';
import {
  type VaultInfo,
  type SubscribeNormalConfig,
  type SubscribePrivateConfig,
  type WalletSigner,
  subscribeNormal,
  subscribePrivateStark,
  claimPeriod,
  pauseNormal,
  pausePrivateStark,
  resumeNormal,
  resumePrivateStark,
  cancelNormal,
  cancelPrivateStark,
  fetchVault,
  computeClaimable,
  computeClaimableAmount,
  goldilocksU64To32,
  ZK_SHIELDED_PROGRAM_ID,
  REFUND_MIN_RESIDUAL,
} from '../services/subscriptionVault';
import {
  receiptFromJSON,
  type ShieldReceipt,
  type PoolConfig,
  ALL_POOLS,
  ALL_POOLS_V3,
  findPoolByPDA,
  createCommitment,
  createCommitmentV3,
  deriveSplitOutputSecrets,
  computeNewRootFromSubtrees,
  computeNewRootFromSubtreesV3,
  slotToEpoch,
  bigintToLeBytes32,
  parseFilledSubtrees,
  pubkeyToField,
} from '../services/denominatedPool';
import { useWalletStore } from './walletStore';
import { useDenominatedPoolStore } from './denominatedPoolStore';
import { vaultDecrypt } from '../utils/crypto/noteVault';
import { scheduleLocalNotification } from '../services/notifications';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface StoredVaultInfo {
  vaultAddress: string;
  retailer: string;
  tokenMint: string;
  rate: string; // bigint as string
  intervalSlots: string; // bigint as string
  isNormalMode: boolean;
  isPrivateMode: boolean;
  subscriberSecret?: string; // encrypted, only for private mode
  /** Service identifier used in the license-key HKDF info. Persisted so the
   *  license key can be re-derived later (LicenseKeyCard) from the SecureStore
   *  subscriber secret + this serviceId. */
  serviceId?: string;
  createdAt: number;
}

interface SubscriptionVaultState {
  // Persisted
  vaults: StoredVaultInfo[];

  // Transient (not persisted)
  isLoading: boolean;
  error: string | null;
  progress: string | null;

  // Actions
  addVault: (vault: StoredVaultInfo) => void;
  removeVault: (vaultAddress: string) => void;
  setLoading: (loading: boolean) => void;
  setError: (error: string | null) => void;
  setProgress: (progress: string | null) => void;
  refreshVault: (vaultAddress: string) => Promise<VaultInfo | null>;
  subscribeNormalAction: (
    config: SubscribeNormalConfig,
    vkHashSubscriber: Uint8Array,
  ) => Promise<string>;
  /** STARK variant: quantum-resistant subscribe_private using pre-verified proof buffer.
   *
   * `subscriberOwnershipCommitment` is the Goldilocks u64 Poseidon commitment of the
   * subscriber secret — same value returned by `StarkProverProvider.generateProof`
   * (circuit 0: subscriber_ownership). It is encoded as [u64_le, 24 zero bytes] and
   * stored on-chain in `vault.subscriber_commitment`; pause/resume/cancel re-derive
   * the sha256 hash from those first 8 bytes to match the circuit-0 proof. */
  subscribePrivateStarkAction: (
    receipt: ShieldReceipt,
    poolConfig: PoolConfig,
    vaultConfig: SubscribePrivateConfig,
    subscriberSecret: bigint,
    subscriberOwnershipCommitment: bigint,
    vkHashSubscriber: Uint8Array,
    starkProofData: { proofBytes: Uint8Array; publicInputs: bigint[]; proofSize: number },
    /**
     * C3 (merkle_path, circuit 3) proof — NEW on-chain hardening requirement.
     * `subscribe_private_stark` now reads a second proof buffer proving the C1
     * commitment is a leaf in the pool tree at the supplied root. publicInputs
     * layout is `[leaf_u64, root_u64, depth(=15)]`; the service derives the
     * ix `merkle_root` from `publicInputs[1]`. Generated by the caller via
     * `generateMerklePathProof`, mirroring unshield_denominated_stark_v3.
     */
    c3ProofData: { proofBytes: Uint8Array; publicInputs: bigint[]; proofSize: number },
    /**
     * Optional v1 stealth meta address (64 bytes: spending_pub || viewing_pub)
     * persisted on-chain in `vault.client_stealth_meta`. When set, cancel
     * routes the residual through `p01_relayer::submit_refund_job` instead
     * of the legacy reshield path. Build with `getOrCreateStealthMetaV1()`.
     */
    clientStealthMeta?: Uint8Array,
    /**
     * Service identifier (Service Registry slot, e.g. 'disney-plus'; falls back
     * to the stream id for custom recipients). Mixed into the license-key HKDF
     * `info` so the on-chain `license_commitment = blake3(deriveLicenseSecret(
     * subscriberSecret, serviceId))` is service-scoped. When omitted, no license
     * commitment is posted (older callers; the vault simply has none).
     */
    serviceId?: string,
  ) => Promise<{ signature: string; vaultAddress: string }>;
  /** STARK variant: quantum-resistant cancel_private_stark using pre-verified proof buffer.
   *
   * Re-shields the refundable balance back into the source pool as fresh notes owned
   * by the subscriber, pays claimable periods to the retailer, and closes the vault.
   * Dust below one denomination is forfeited (privacy tradeoff). */
  cancelPrivateStarkAction: (
    vaultAddress: string,
    subscriberSecret: bigint,
    starkProofData: { proofBytes: Uint8Array; commitment: bigint; proofSize: number },
  ) => Promise<string>;
  claimPeriodAction: (vaultAddress: string) => Promise<string>;
  pauseNormalAction: (vaultAddress: string) => Promise<string>;
  /** STARK variant: quantum-resistant pause_private using pre-verified proof buffer */
  pausePrivateStarkAction: (
    vaultAddress: string,
    starkProofData: { proofBytes: Uint8Array; commitment: bigint; proofSize: number },
  ) => Promise<string>;
  resumeNormalAction: (vaultAddress: string) => Promise<string>;
  /** STARK variant: quantum-resistant resume_private using pre-verified proof buffer */
  resumePrivateStarkAction: (
    vaultAddress: string,
    starkProofData: { proofBytes: Uint8Array; commitment: bigint; proofSize: number },
  ) => Promise<string>;
  cancelNormalAction: (vaultAddress: string, retailer: string) => Promise<string>;
  /** Force-clear a stuck subscribe/pause/resume/claim. Use when a flow was interrupted and isLoading refuses to release. */
  resetOperationState: () => void;
  /** Soft reset for wallet switches — clears the in-memory vault list but PRESERVES SecureStore secrets so archive/restore can rehydrate. */
  softReset: () => void;
  /** Scan on-chain for vaults whose subscriber commitment matches any of our spent/transferred notes (recover orphaned subscriptions).
   *
   * When `computeStarkCommitment` is supplied, STARK vaults (Goldilocks u64 commitment)
   * are also matched alongside legacy BN254 vaults — this is the cross-device recovery
   * path (seed → notes → subscriptions). Returns the newly-recovered `VaultInfo`s so the
   * caller can synthesize local Stream records. */
  recoverOrphanedVaults: (
    computeStarkCommitment?: (secretDecimal: string) => Promise<string>,
  ) => Promise<{ recovered: number; scanned: number; newVaults: VaultInfo[] }>;
  reset: () => void;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Secure secret storage (SecureStore instead of AsyncStorage)
// ---------------------------------------------------------------------------

const SECURE_SECRET_PREFIX = 'p01_vault_secret_';

async function saveSecretSecurely(vaultAddress: string, secret: string): Promise<void> {
  await SecureStore.setItemAsync(`${SECURE_SECRET_PREFIX}${vaultAddress}`, secret);
}

async function loadSecretSecurely(vaultAddress: string): Promise<string | null> {
  return SecureStore.getItemAsync(`${SECURE_SECRET_PREFIX}${vaultAddress}`);
}

/**
 * Load the per-vault subscriber master note secret (decimal string) from
 * SecureStore. Used by the LicenseKeyCard to re-derive the license key under
 * the commitment scheme (`encodeLicenseKey(deriveLicenseSecret(secret,
 * serviceId))`). Returns null when no secret is stored for this vault (e.g.
 * classic vaults, or a vault recovered without its secret).
 */
export async function loadVaultSubscriberSecret(vaultAddress: string): Promise<string | null> {
  return loadSecretSecurely(vaultAddress);
}

async function deleteSecretSecurely(vaultAddress: string): Promise<void> {
  await SecureStore.deleteItemAsync(`${SECURE_SECRET_PREFIX}${vaultAddress}`);
}

// ---------------------------------------------------------------------------
// Wallet-scoped vault archival (prevents subscription loss on wallet switch)
// ---------------------------------------------------------------------------

const VAULT_ARCHIVE_PREFIX = 'p01_vaults_archive_';

/**
 * Archive current vault list for a specific wallet address before switching.
 * SecureStore secrets (keyed by vaultPDA) are NOT touched — they survive the switch
 * so restore can rehydrate full vault state.
 */
export async function archiveVaultsForWallet(walletAddress: string): Promise<void> {
  if (!walletAddress) return;
  const { vaults } = useSubscriptionVaultStore.getState();
  if (vaults.length === 0) return;
  try {
    await AsyncStorage.setItem(`${VAULT_ARCHIVE_PREFIX}${walletAddress}`, JSON.stringify(vaults));
  } catch (err) {
    console.error('[VaultStore] Failed to archive vaults:', (err as Error).message);
  }
}

/**
 * Restore archived vaults for a wallet address after switching back.
 * Merges with any existing vaults (deduplicates by vaultAddress).
 */
export async function restoreVaultsForWallet(walletAddress: string): Promise<void> {
  if (!walletAddress) return;
  try {
    const raw = await AsyncStorage.getItem(`${VAULT_ARCHIVE_PREFIX}${walletAddress}`);
    if (!raw) return;
    const archived: StoredVaultInfo[] = JSON.parse(raw);
    if (!Array.isArray(archived) || archived.length === 0) return;

    const { vaults: currentVaults } = useSubscriptionVaultStore.getState();
    const existing = new Set(currentVaults.map(v => v.vaultAddress));
    const newVaults = archived.filter(v => !existing.has(v.vaultAddress));
    if (newVaults.length > 0) {
      useSubscriptionVaultStore.setState({ vaults: [...currentVaults, ...newVaults] });
    }
  } catch (err) {
    console.error('[VaultStore] Failed to restore vaults:', (err as Error).message);
  }
}

/** Format lamports as SOL for notification display */
function formatRateSOL(rateLamports: string | bigint): string {
  const lamports = typeof rateLamports === 'string' ? Number(rateLamports) : Number(rateLamports);
  if (!Number.isFinite(lamports) || lamports <= 0) return '0 SOL';
  return `${(lamports / 1_000_000_000).toFixed(4)} SOL`;
}

/** Fire a subscription lifecycle notification (fire-and-forget, never throws) */
function notifySubscriptionEvent(title: string, body: string, extra?: Record<string, unknown>): void {
  scheduleLocalNotification(title, body, {
    category: 'transaction',
    channelId: 'payments',
    ...extra,
  }).catch(() => {});
}

// NOTE(Privy-removal, spec §3 Phase 1): `getWalletSignerIfPrivy()` is gone. Every
// wallet is a local Ed25519 keypair, so the service helpers below fall back to
// `getKeypair()` internally whenever the optional `WalletSigner` arg is undefined.
// The external (software-wallet) signer path returns in Phase 3.

// ---------------------------------------------------------------------------
// Store
// ---------------------------------------------------------------------------

export const useSubscriptionVaultStore = create<SubscriptionVaultState>()(
  persist(
    (set, get) => ({
      // Initial state
      vaults: [],
      isLoading: false,
      error: null,
      progress: null,

      // ------------------------------------------------------------------
      // Vault Management
      // ------------------------------------------------------------------

      addVault: (vault) => {
        set(state => ({
          vaults: [vault, ...state.vaults],
          error: null,
        }));
      },

      removeVault: (vaultAddress) => {
        deleteSecretSecurely(vaultAddress).catch(() => {});
        set(state => ({
          vaults: state.vaults.filter(v => v.vaultAddress !== vaultAddress),
        }));
      },

      setLoading: (loading) => set({ isLoading: loading }),
      setError: (error) => set({ error }),
      setProgress: (progress) => set({ progress }),

      // ------------------------------------------------------------------
      // Refresh Vault
      // ------------------------------------------------------------------

      refreshVault: async (vaultAddress) => {
        try {
          const vaultPDA = new PublicKey(vaultAddress);
          const vault = await fetchVault(vaultPDA);
          return vault;
        } catch (err) {
          console.error('[SubscriptionVault] refreshVault error:', err);
          return null;
        }
      },

      // ------------------------------------------------------------------
      // Subscribe Normal
      // ------------------------------------------------------------------

      subscribeNormalAction: async (config, vkHashSubscriber) => {
        set({ isLoading: true, error: null, progress: 'Preparing...' });

        try {
          const walletSigner: WalletSigner | undefined = undefined; // Privy removed — local keypair only
          const sig = await subscribeNormal(
            config,
            vkHashSubscriber,
            (step) => {
              set({ progress: step });
            },
            walletSigner,
          );

          // Add vault to store
          const { getPublicKey } = await import('../services/solana/wallet');
          const subscriberPubkey = await getPublicKey();
          if (!subscriberPubkey) throw new Error('Failed to get wallet pubkey');

          const { deriveVaultPDA } = await import('../services/subscriptionVault');
          const [vaultPDA] = deriveVaultPDA(
            config.retailer,
            new PublicKey(subscriberPubkey),
            config.tokenMint
          );

          const storedVault: StoredVaultInfo = {
            vaultAddress: vaultPDA.toBase58(),
            retailer: config.retailer.toBase58(),
            tokenMint: config.tokenMint.toBase58(),
            rate: config.rate.toString(),
            intervalSlots: config.intervalSlots.toString(),
            isNormalMode: true,
            isPrivateMode: false,
            createdAt: Date.now(),
          };

          set(state => ({
            isLoading: false,
            progress: null,
            vaults: [storedVault, ...state.vaults.filter(v => v.vaultAddress !== storedVault.vaultAddress)],
          }));

          // Sync the new vault as a Stream record so the Streams tab reflects
          // the subscription immediately (otherwise it stays invisible until
          // the next on-chain rescan / app reboot). Best-effort, non-fatal.
          try {
            const { fetchVault } = await import('../services/subscriptionVault');
            const { upsertStreamFromVault } = await import('../services/solana/streams');
            const vaultInfo = await fetchVault(vaultPDA);
            if (vaultInfo) await upsertStreamFromVault(vaultInfo);
          } catch (e) {
            console.warn('[SubscriptionVault] stream sync after subscribeNormal failed (non-fatal):', e);
          }

          notifySubscriptionEvent(
            'Subscription Active',
            `Subscribed at ${formatRateSOL(config.rate)} per period`,
            { transactionId: sig },
          );

          return sig;
        } catch (err) {
          console.error('[SubscriptionVault] subscribeNormal error:', err);
          set({ isLoading: false, progress: null, error: (err as Error).message });
          throw err;
        }
      },

      // ------------------------------------------------------------------
      // Subscribe Private (STARK — quantum-resistant)
      // ------------------------------------------------------------------

      subscribePrivateStarkAction: async (
        receipt,
        poolConfig,
        vaultConfig,
        subscriberSecret,
        subscriberOwnershipCommitment,
        vkHashSubscriber,
        starkProofData,
        c3ProofData,
        clientStealthMeta,
        serviceId,
      ) => {
        set({ isLoading: true, error: null, progress: 'Preparing STARK subscription...' });

        if (__DEV__) {
          console.log('[Sub:Create:Store] subscribePrivateStarkAction begin', {
            poolPDA: poolConfig.poolPDA.toBase58(),
            poolVersion: (poolConfig as any).version ?? 'v2',
            tokenMint: poolConfig.tokenMint.toBase58(),
            denomination: poolConfig.denomination,
            retailer: vaultConfig.retailer.toBase58().slice(0, 8) + '…',
            rate: vaultConfig.rate.toString(),
            intervalSlots: vaultConfig.intervalSlots.toString(),
            commitmentBigintPrefix: subscriberOwnershipCommitment.toString(16).slice(0, 16),
            vkHashPrefix: Buffer.from(vkHashSubscriber).slice(0, 4).toString('hex'),
            proofSize: starkProofData.proofSize,
            hasStealthMeta: !!clientStealthMeta,
          });
        }

        try {
          const walletSigner: WalletSigner | undefined = undefined; // Privy removed — local keypair only

          // License key commitment (commitment scheme): derive a per-subscriber
          // 128-bit licenseSecret from the SAME master note secret the vault's
          // subscriber_commitment is derived from, scoped by serviceId, then post
          // blake3(licenseSecret) on-chain. The chain stores it verbatim (no
          // verification); a merchant later checks blake3(decode(presentedKey))
          // against it off-chain — NO shared secret anywhere. The displayed key
          // (LicenseKeyCard) is encodeLicenseKey(licenseSecret) from the same inputs.
          let licenseCommitmentBytes: Uint8Array | undefined;
          if (serviceId) {
            const { deriveLicenseSecret, licenseCommitment } = await import('../services/license/derive');
            const licenseSecret = deriveLicenseSecret(subscriberSecret, serviceId);
            licenseCommitmentBytes = licenseCommitment(licenseSecret);
          }

          const sig = await subscribePrivateStark(
            receipt,
            poolConfig,
            vaultConfig,
            subscriberOwnershipCommitment,
            vkHashSubscriber,
            starkProofData,
            c3ProofData,
            (step) => {
              set({ progress: step });
            },
            walletSigner,
            clientStealthMeta,
            licenseCommitmentBytes,
          );

          // Add vault to store — PDA keyed by the Goldilocks subscriber commitment,
          // same encoding used on-chain (`u64_le || 24 zero bytes`).
          const subscriberCommitmentBytes = goldilocksU64To32(subscriberOwnershipCommitment);

          const { deriveVaultPDA } = await import('../services/subscriptionVault');
          const [vaultPDA] = deriveVaultPDA(
            vaultConfig.retailer,
            subscriberCommitmentBytes,
            poolConfig.tokenMint
          );

          const storedVault: StoredVaultInfo = {
            vaultAddress: vaultPDA.toBase58(),
            retailer: vaultConfig.retailer.toBase58(),
            tokenMint: poolConfig.tokenMint.toBase58(),
            rate: vaultConfig.rate.toString(),
            intervalSlots: vaultConfig.intervalSlots.toString(),
            isNormalMode: false,
            isPrivateMode: true,
            serviceId,
            createdAt: Date.now(),
          };

          // Save secret to SecureStore (not AsyncStorage)
          await saveSecretSecurely(vaultPDA.toBase58(), subscriberSecret.toString());
          if (__DEV__) {
            // Verify the round-trip — SecureStore can silently fail on locked
            // device or 2 KB key-size cap. A vault that exists on-chain but
            // whose secret isn't retrievable later is the canonical
            // "subscription stops renewing" symptom.
            try {
              const roundTrip = await loadSecretSecurely(vaultPDA.toBase58());
              const ok = roundTrip === subscriberSecret.toString();
              console.log('[Sub:Create:Store] vault secret saved', {
                vaultPDA: vaultPDA.toBase58(),
                secretRoundTripOk: ok,
                storedLen: roundTrip?.length ?? 0,
              });
              if (!ok) {
                console.warn('[Sub:Create:Store] SECRET ROUND-TRIP MISMATCH — renewal will fail');
              }
            } catch (e) {
              console.warn('[Sub:Create:Store] secret round-trip check threw', e);
            }
          }

          set(state => ({
            vaults: [storedVault, ...state.vaults.filter(v => v.vaultAddress !== storedVault.vaultAddress)],
          }));

          // Sync the new vault as a Stream record so the Streams tab reflects
          // the subscription immediately. Best-effort, non-fatal.
          try {
            const { fetchVault } = await import('../services/subscriptionVault');
            const { upsertStreamFromVault } = await import('../services/solana/streams');
            const vaultInfo = await fetchVault(vaultPDA);
            if (__DEV__) {
              console.log('[Sub:Create:Store] stream sync', {
                vaultFetched: !!vaultInfo,
                vaultPDA: vaultPDA.toBase58(),
              });
            }
            if (vaultInfo) await upsertStreamFromVault(vaultInfo);
          } catch (e) {
            console.warn('[SubscriptionVault] stream sync after subscribePrivateStark failed (non-fatal):', e);
          }

          notifySubscriptionEvent(
            'Subscription Active',
            `Subscribed at ${formatRateSOL(vaultConfig.rate)} per period`,
            { transactionId: sig },
          );

          if (__DEV__) {
            console.log('[Sub:Create:Store] subscribePrivateStarkAction success', {
              vaultPDA: vaultPDA.toBase58(),
              sigPrefix: sig.slice(0, 16),
              storedVaultCount: get().vaults.length,
            });
          }
          return { signature: sig, vaultAddress: vaultPDA.toBase58() };
        } catch (err) {
          console.error('[SubscriptionVault] subscribePrivateStark error:', err);
          if (__DEV__) {
            console.warn('[Sub:Create:Store] FAILED', {
              message: (err as Error).message,
              poolPDA: poolConfig.poolPDA.toBase58(),
              poolVersion: (poolConfig as any).version ?? 'v2',
            });
          }
          set({ error: (err as Error).message });
          throw err;
        } finally {
          // Always clear transient spinner — prevents a stuck UI if the STARK
          // flow throws mid-step (prover, RPC, signer, notification, etc.).
          set({ isLoading: false, progress: null });
        }
      },

      // ------------------------------------------------------------------
      // Claim Period
      // ------------------------------------------------------------------

      claimPeriodAction: async (vaultAddress) => {
        set({ isLoading: true, error: null, progress: 'Claiming...' });

        try {
          const vaultPDA = new PublicKey(vaultAddress);
          const walletSigner: WalletSigner | undefined = undefined; // Privy removed — local keypair only
          const sig = await claimPeriod(
            vaultPDA,
            (step) => {
              set({ progress: step });
            },
            walletSigner,
          );

          set({ isLoading: false, progress: null });

          const storedVault = get().vaults.find(v => v.vaultAddress === vaultAddress);
          const rateLabel = storedVault ? formatRateSOL(storedVault.rate) : 'SOL';
          notifySubscriptionEvent(
            'Payment Claimed',
            `${rateLabel} claimed from subscription`,
            { transactionId: sig },
          );

          return sig;
        } catch (err) {
          console.error('[SubscriptionVault] claimPeriod error:', err);
          set({ isLoading: false, progress: null, error: (err as Error).message });
          throw err;
        }
      },

      // ------------------------------------------------------------------
      // Pause Normal
      // ------------------------------------------------------------------

      pauseNormalAction: async (vaultAddress) => {
        set({ isLoading: true, error: null, progress: 'Pausing...' });

        try {
          const vaultPDA = new PublicKey(vaultAddress);
          const walletSigner: WalletSigner | undefined = undefined; // Privy removed — local keypair only
          const sig = await pauseNormal(
            vaultPDA,
            (step) => {
              set({ progress: step });
            },
            walletSigner,
          );

          set({ isLoading: false, progress: null });

          notifySubscriptionEvent(
            'Subscription Paused',
            'Your subscription has been paused',
            { transactionId: sig },
          );

          return sig;
        } catch (err) {
          console.error('[SubscriptionVault] pauseNormal error:', err);
          set({ isLoading: false, progress: null, error: (err as Error).message });
          throw err;
        }
      },

      // ------------------------------------------------------------------
      // Pause Private (STARK — quantum-resistant)
      // ------------------------------------------------------------------

      pausePrivateStarkAction: async (vaultAddress, starkProofData) => {
        set({ isLoading: true, error: null, progress: 'Pausing (STARK)...' });

        try {
          const vaultPDA = new PublicKey(vaultAddress);
          const walletSigner: WalletSigner | undefined = undefined; // Privy removed — local keypair only
          const sig = await pausePrivateStark(
            vaultPDA,
            starkProofData,
            (step) => {
              set({ progress: step });
            },
            walletSigner,
          );

          notifySubscriptionEvent(
            'Subscription Paused',
            'Your subscription has been paused',
            { transactionId: sig },
          );

          return sig;
        } catch (err) {
          console.error('[SubscriptionVault] pausePrivateStark error:', err);
          set({ error: (err as Error).message });
          throw err;
        } finally {
          set({ isLoading: false, progress: null });
        }
      },

      // ------------------------------------------------------------------
      // Resume Normal
      // ------------------------------------------------------------------

      resumeNormalAction: async (vaultAddress) => {
        set({ isLoading: true, error: null, progress: 'Resuming...' });

        try {
          const vaultPDA = new PublicKey(vaultAddress);
          const walletSigner: WalletSigner | undefined = undefined; // Privy removed — local keypair only
          const sig = await resumeNormal(
            vaultPDA,
            (step) => {
              set({ progress: step });
            },
            walletSigner,
          );

          set({ isLoading: false, progress: null });

          notifySubscriptionEvent(
            'Subscription Resumed',
            'Your subscription has been resumed',
            { transactionId: sig },
          );

          return sig;
        } catch (err) {
          console.error('[SubscriptionVault] resumeNormal error:', err);
          set({ isLoading: false, progress: null, error: (err as Error).message });
          throw err;
        }
      },

      // ------------------------------------------------------------------
      // Resume Private (STARK — quantum-resistant)
      // ------------------------------------------------------------------

      resumePrivateStarkAction: async (vaultAddress, starkProofData) => {
        set({ isLoading: true, error: null, progress: 'Resuming (STARK)...' });

        try {
          const vaultPDA = new PublicKey(vaultAddress);
          const walletSigner: WalletSigner | undefined = undefined; // Privy removed — local keypair only
          const sig = await resumePrivateStark(
            vaultPDA,
            starkProofData,
            (step) => {
              set({ progress: step });
            },
            walletSigner,
          );

          notifySubscriptionEvent(
            'Subscription Resumed',
            'Your subscription has been resumed',
            { transactionId: sig },
          );

          return sig;
        } catch (err) {
          console.error('[SubscriptionVault] resumePrivateStark error:', err);
          set({ error: (err as Error).message });
          throw err;
        } finally {
          set({ isLoading: false, progress: null });
        }
      },

      // ------------------------------------------------------------------
      // Cancel Private (STARK — quantum-resistant, re-shields refundable)
      // ------------------------------------------------------------------

      cancelPrivateStarkAction: async (vaultAddress, subscriberSecret, starkProofData) => {
        set({ isLoading: true, error: null, progress: 'Cancelling (STARK)...' });

        try {
          const vaultPDA = new PublicKey(vaultAddress);
          const connection = getConnection();

          // 1. Fetch vault state to compute claimable/refundable
          const vault = await fetchVault(vaultPDA);
          if (!vault) throw new Error('Vault not found on-chain');
          if (!vault.isPrivateMode) throw new Error('Vault is not in private mode');
          if (!vault.sourcePool) throw new Error('Vault has no source pool');

          // 2. Resolve source pool config (search V2 + V3 lists — V3 vaults
          //    created on V4 pools post-2026-05-07 seed bump are NOT in V2 list).
          //    We still need target_pool/target_tree for the refund-job path
          //    so the keeper knows where to deliver the note.
          const sourcePool = findPoolByPDA(vault.sourcePool);
          if (!sourcePool) throw new Error(`Source pool not found: ${vault.sourcePool}`);
          const sourceIsV3 = sourcePool.version === 'v3';
          console.log('[Sub:Cancel] resolved source pool', {
            poolPDA: sourcePool.poolPDA.toBase58(),
            version: sourcePool.version,
            denomination: sourcePool.denomination,
            hasStealthMeta: !!vault.clientStealthMeta,
          });

          // 3. Compute refundable amount (matches on-chain handler math exactly)
          const currentSlot = await connection.getSlot('confirmed');
          const claimable = BigInt(computeClaimable(vault, currentSlot));
          const totalOwed = (vault.claimedPeriods + claimable) * vault.rate;
          const refundable = vault.totalDeposited > totalOwed
            ? vault.totalDeposited - totalOwed
            : 0n;

          // Decide path: refund-via-relayer only when the vault has a
          // stealth meta AND the residual is large enough to cover keeper
          // fees + RefundJob rent. Otherwise fall back to legacy reshield
          // (or dust-forfeit for sub-denomination residuals).
          const useRefundJob =
            !!vault.clientStealthMeta && refundable >= REFUND_MIN_RESIDUAL;

          if (useRefundJob) {
            console.log('[Sub:Cancel] refund-via-relayer path', {
              refundableLamports: refundable.toString(),
              targetPool: sourcePool.poolPDA.toBase58(),
            });

            // No commitments / new roots — the keeper computes those once it
            // picks up the RefundJob. Caller only ships the cancel ix.
            const walletSigner: WalletSigner | undefined = undefined; // Privy removed — local keypair only
            const sig = await cancelPrivateStark(
              vaultPDA,
              new PublicKey(vault.retailer),
              { poolPDA: sourcePool.poolPDA, treePDA: sourcePool.treePDA },
              [],
              [],
              starkProofData,
              (step) => { set({ progress: step }); },
              walletSigner,
              true, // useRefundJob
            );

            await deleteSecretSecurely(vaultAddress);
            set(state => ({
              vaults: state.vaults.filter(v => v.vaultAddress !== vaultAddress),
            }));

            notifySubscriptionEvent(
              'Subscription Cancelled',
              'Refund queued — note will land privately in a few minutes',
              { transactionId: sig },
            );

            return sig;
          }

          // ───── Legacy reshield path (pre-stealth-meta vaults or dust) ─────
          const notesToReshield = Number(refundable / sourcePool.denominationAtomic);

          // 4. Derive deterministic output secrets from subscriber secret
          const outputSecrets = deriveSplitOutputSecrets(subscriberSecret, notesToReshield);

          // 5. Compute commitments + sequential new Merkle roots — pick V2/V3
          //    hash family based on the source pool. Mismatch silently fails
          //    on-chain at re-shield root verification.
          set({ progress: 'Computing re-shield commitments...' });
          const currentEpoch = slotToEpoch(currentSlot);
          const tokenMintField = pubkeyToField(sourcePool.tokenMint);
          const commitFn = sourceIsV3 ? createCommitmentV3 : createCommitment;
          const newRootFn = sourceIsV3 ? computeNewRootFromSubtreesV3 : computeNewRootFromSubtrees;

          const outputCommitments: bigint[] = [];
          const newReceipts: ShieldReceipt[] = [];

          for (let i = 0; i < notesToReshield; i++) {
            const secret = outputSecrets[i];
            const nullifierPreimage = poseidon2([secret, BigInt(i)]);
            const commitment = commitFn(
              nullifierPreimage, secret, currentEpoch, tokenMintField,
            );
            outputCommitments.push(commitment);
            newReceipts.push({
              secret,
              nullifierPreimage,
              depositEpoch: currentEpoch,
              tokenMint: tokenMintField,
              commitment,
              leafIndex: -1,
              denomination: sourcePool.denominationAtomic,
              pool: sourcePool.poolPDA.toBase58(),
              token: sourcePool.token,
              denominationHuman: sourcePool.denomination,
              shieldedAt: Date.now(),
            });
          }

          let commitmentBytes: Uint8Array[] = [];
          let rootBytes: Uint8Array[] = [];
          if (notesToReshield > 0) {
            const treeAccount = await connection.getAccountInfo(sourcePool.treePDA);
            if (!treeAccount) throw new Error('Source Merkle tree account not found');
            let { leafCount, subtrees } = parseFilledSubtrees(treeAccount.data);

            commitmentBytes = outputCommitments.map(c => new Uint8Array(bigintToLeBytes32(c)));
            for (let i = 0; i < notesToReshield; i++) {
              const { newRoot, updatedSubtrees } = newRootFn(
                outputCommitments[i], leafCount, subtrees,
              );
              rootBytes.push(new Uint8Array(bigintToLeBytes32(newRoot)));
              subtrees = updatedSubtrees;
              leafCount += 1;
            }
          }

          // 6. Call on-chain cancel (STARK verify → cancel → close buffer)
          const walletSigner: WalletSigner | undefined = undefined; // Privy removed — local keypair only
          const sig = await cancelPrivateStark(
            vaultPDA,
            new PublicKey(vault.retailer),
            { poolPDA: sourcePool.poolPDA, treePDA: sourcePool.treePDA },
            commitmentBytes,
            rootBytes,
            starkProofData,
            (step) => { set({ progress: step }); },
            walletSigner,
          );

          // 7. Save re-shielded notes to denom pool store + remove vault
          if (newReceipts.length > 0) {
            useDenominatedPoolStore.getState().addReshieldedNotes(newReceipts, sourcePool);
          }
          await deleteSecretSecurely(vaultAddress);

          set(state => ({
            vaults: state.vaults.filter(v => v.vaultAddress !== vaultAddress),
          }));

          notifySubscriptionEvent(
            'Subscription Cancelled',
            notesToReshield > 0
              ? `Cancelled and re-shielded ${notesToReshield} note${notesToReshield === 1 ? '' : 's'}`
              : 'Your subscription has been cancelled',
            { transactionId: sig },
          );

          return sig;
        } catch (err) {
          console.error('[SubscriptionVault] cancelPrivateStark error:', err);
          set({ error: (err as Error).message });
          throw err;
        } finally {
          set({ isLoading: false, progress: null });
        }
      },

      // ------------------------------------------------------------------
      // Cancel Normal
      // ------------------------------------------------------------------

      cancelNormalAction: async (vaultAddress, retailer) => {
        set({ isLoading: true, error: null, progress: 'Cancelling...' });

        try {
          const vaultPDA = new PublicKey(vaultAddress);
          const retailerKey = new PublicKey(retailer);
          const walletSigner: WalletSigner | undefined = undefined; // Privy removed — local keypair only
          const sig = await cancelNormal(
            vaultPDA,
            retailerKey,
            (step) => {
              set({ progress: step });
            },
            walletSigner,
          );

          // Remove vault from store
          set(state => ({
            isLoading: false,
            progress: null,
            vaults: state.vaults.filter(v => v.vaultAddress !== vaultAddress),
          }));

          notifySubscriptionEvent(
            'Subscription Cancelled',
            'Your subscription has been cancelled',
            { transactionId: sig },
          );

          return sig;
        } catch (err) {
          console.error('[SubscriptionVault] cancelNormal error:', err);
          set({ isLoading: false, progress: null, error: (err as Error).message });
          throw err;
        }
      },

      resetOperationState: () => {
        set({ isLoading: false, progress: null, error: null });
      },

      recoverOrphanedVaults: async (computeStarkCommitment) => {
        // Matches two commitment families:
        //  • BN254/legacy: poseidon2([secret, 1234567890]) — pre-STARK vaults
        //  • STARK: Goldilocks u64 returned by circuit 0, packed via goldilocksU64To32
        //    (u64 little-endian in bytes[0..8], zero-padded to 32). Requires the STARK
        //    prover — pass `computeStarkCommitment` from `useStarkProver().computeCommitment`.
        const connection = getConnection();
        const { notes } = useDenominatedPoolStore.getState();
        if (__DEV__) {
          console.log('[Sub:Recovery] begin', {
            totalNotes: notes.length,
            hasStarkProver: !!computeStarkCommitment,
            existingVaults: get().vaults.length,
          });
        }

        // Candidate notes — anything we have a receipt for, even if marked spent. On a
        // new device the seed-based `rescanPool` reconstructs spent notes too, which is
        // how we find subscriptions that consumed a note on another device.
        type Candidate = { secret: bigint; legacyHex: string; starkHex?: string };
        const candidates: Candidate[] = [];
        for (const n of notes) {
          try {
            const receipt = receiptFromJSON(vaultDecrypt(n.receiptJSON));
            const secret = receipt.secret;
            const legacyCommitment = poseidon2([secret, 1234567890n]);
            const legacyBytes = new Uint8Array(32);
            let tmp = legacyCommitment;
            for (let i = 0; i < 32; i++) { legacyBytes[i] = Number(tmp & 0xFFn); tmp >>= 8n; }
            candidates.push({
              secret,
              legacyHex: Buffer.from(legacyBytes).toString('hex'),
            });
          } catch {
            // skip notes whose receipt can't be decrypted (different wallet etc.)
          }
        }

        if (candidates.length === 0) return { recovered: 0, scanned: 0, newVaults: [] };

        // STARK commitments: computed lazily via the prover (WebView round-trip per
        // note, ~200-400ms each). Skipped if no prover supplied.
        if (computeStarkCommitment) {
          for (const c of candidates) {
            try {
              // DECIMAL, not hex. `compute_stark_commitment` (stark/src/lib.rs:133)
              // returns `commitment.as_int().to_string()`, and StarkProver posts that
              // string back verbatim. Parsing it as hex silently succeeds — every
              // decimal digit is valid hex — and yields a different u64 that matches
              // no vault on chain, which made ZK subscription recovery impossible
              // while reporting "recovered: 0" as if the user simply had none.
              // The other consumer of this same WASM output agrees: see
              // `feltStringToCommitment` in services/quantumWallet/index.ts:308.
              const commitmentDecimal = await computeStarkCommitment(c.secret.toString());
              const bytes = goldilocksU64To32(BigInt(commitmentDecimal));
              c.starkHex = Buffer.from(bytes).toString('hex');
            } catch (err) {
              console.warn('[recoverOrphanedVaults] STARK commitment failed for candidate:', (err as Error).message);
            }
          }
        }

        // Fetch all subscription vault accounts owned by the program. Anchor accounts
        // start with an 8-byte discriminator; we filter further in-memory.
        let allAccounts: Awaited<ReturnType<typeof connection.getProgramAccounts>>;
        try {
          allAccounts = await connection.getProgramAccounts(ZK_SHIELDED_PROGRAM_ID, {
            commitment: 'confirmed',
          });
        } catch (err) {
          throw new Error(`On-chain scan failed: ${(err as Error).message}`);
        }

        // Borsh `Option<T>` is VARIABLE-width: `None` = a single `0` tag byte
        // (no value bytes). A private-mode vault always has
        // `subscriber_pubkey = None` (1 byte at offset 8), so
        // `subscriber_commitment`'s tag sits at offset 9 and its 32 value bytes
        // at offset 10. (The old 41/42 assumed `subscriber_pubkey` was a
        // FIXED 33-byte field — wrong for Borsh — so the tag check at 41 read
        // zero padding and dropped EVERY private vault.) Verified on live
        // devnet vaults: byte[9] == 1 and the commitment is at 10..42.
        const COMMITMENT_TAG_OFFSET = 9;
        const COMMITMENT_BYTES_OFFSET = 10;

        let recovered = 0;
        const newStoredVaults: StoredVaultInfo[] = [];
        const newVaults: VaultInfo[] = [];
        const { vaults: existing } = get();
        const existingAddrs = new Set(existing.map(v => v.vaultAddress));

        for (const acc of allAccounts) {
          const data = acc.account.data;
          if (data.length < COMMITMENT_BYTES_OFFSET + 32) continue;
          if (data[COMMITMENT_TAG_OFFSET] !== 1) continue; // not a private-mode vault

          const onchainHex = data.slice(COMMITMENT_BYTES_OFFSET, COMMITMENT_BYTES_OFFSET + 32).toString('hex');
          const match = candidates.find(c => c.legacyHex === onchainHex || c.starkHex === onchainHex);
          if (!match) continue;

          const vaultPDA = acc.pubkey;
          const vaultAddress = vaultPDA.toBase58();
          if (existingAddrs.has(vaultAddress)) continue;

          const info = await fetchVault(vaultPDA).catch(() => null);
          if (!info) continue;

          await saveSecretSecurely(vaultAddress, match.secret.toString());

          newStoredVaults.push({
            vaultAddress,
            retailer: info.retailer,
            tokenMint: info.tokenMint,
            rate: info.rate.toString(),
            intervalSlots: info.intervalSlots.toString(),
            isNormalMode: false,
            isPrivateMode: true,
            createdAt: Date.now(),
          });
          newVaults.push(info);
          recovered += 1;
        }

        if (newStoredVaults.length > 0) {
          set(state => ({ vaults: [...newStoredVaults, ...state.vaults] }));
        }

        if (__DEV__) {
          console.log('[Sub:Recovery] done', {
            scanned: allAccounts.length,
            recovered,
            candidateCount: candidates.length,
            candidatesWithStark: candidates.filter(c => !!c.starkHex).length,
            newVaultAddresses: newStoredVaults.map(v => v.vaultAddress),
          });
        }
        return { recovered, scanned: allAccounts.length, newVaults };
      },

      softReset: () => {
        set({
          vaults: [],
          isLoading: false,
          error: null,
          progress: null,
        });
      },

      reset: () => {
        // Delete all secrets from SecureStore
        const { vaults } = get();
        for (const v of vaults) {
          deleteSecretSecurely(v.vaultAddress).catch(() => {});
        }
        set({
          vaults: [],
          isLoading: false,
          error: null,
          progress: null,
        });
      },
    }),
    {
      name: 'p01-subscription-vault',
      version: 1,
      storage: createJSONStorage(() => AsyncStorage),
      partialize: (state) => ({
        vaults: state.vaults,
        // subscriberSecrets are now stored in SecureStore, not AsyncStorage
      }),
    },
  ),
);
